"""TEC Diocese → County mapping for multi-diocese states.
Built from Wikipedia diocese infobox territory data.
Format: STATE_COUNTY_DIOCESE[state_abbr][county_name] = diocese_name
For single-diocese states, no mapping needed — state default works.
County names should NOT include "County" suffix.
"""
STATE_COUNTY_DIOCESE = {
    "TX": {
        "Brazoria": "Texas", "Brazos": "Texas", "Burleson": "Texas", "Chambers": "Texas",
        "Fort Bend": "Texas", "Galveston": "Texas", "Grimes": "Texas", "Hardin": "Texas",
        "Harris": "Texas", "Jefferson": "Texas", "Liberty": "Texas", "Madison": "Texas",
        "Matagorda": "Texas", "Montgomery": "Texas", "Orange": "Texas", "Robertson": "Texas",
        "Travis": "Texas", "Walker": "Texas", "Waller": "Texas", "Washington": "Texas",
        "Wharton": "Texas", "Austin": "Texas", "Colorado": "Texas", "Fayette": "Texas",
        "Bastrop": "Texas", "Caldwell": "Texas", "Hays": "Texas", "Williamson": "Texas",
        "Lee": "Texas", "Milam": "Texas", "Bell": "Texas", "McLennan": "Texas",
        "Falls": "Texas", "Limestone": "Texas", "Freestone": "Texas", "Leon": "Texas",
        "Houston": "Texas", "Trinity": "Texas", "Polk": "Texas", "San Jacinto": "Texas",
        "Angelina": "Texas", "Nacogdoches": "Texas", "Shelby": "Texas", "San Augustine": "Texas",
        "Sabine": "Texas", "Newton": "Texas", "Jasper": "Texas", "Tyler": "Texas",
        "Tarrant": "Texas", "Johnson": "Texas", "Hill": "Texas", "Navarro": "Texas",
        "Henderson": "Texas", "Anderson": "Texas", "Cherokee": "Texas", "Smith": "Texas",
        "Gregg": "Texas", "Rusk": "Texas", "Panola": "Texas", "Harrison": "Texas",
        "Marion": "Texas", "Upshur": "Texas", "Wood": "Texas", "Van Zandt": "Texas",
        "Kaufman": "Texas", "Hunt": "Texas", "Rains": "Texas", "Hopkins": "Texas",
        "Delta": "Texas", "Lamar": "Texas", "Red River": "Texas", "Bowie": "Texas",
        "Cass": "Texas", "Morris": "Texas", "Camp": "Texas", "Franklin": "Texas",
        "Titus": "Texas", "Denton": "Texas", "Collin": "Texas", "Rockwall": "Texas",
        "Parker": "Texas", "Wise": "Texas", "Cooke": "Texas", "Grayson": "Texas",
        "Fannin": "Texas",
        "Dallas": "Dallas", "Ellis": "Dallas",
        "Bexar": "West Texas", "El Paso": "West Texas", "Midland": "West Texas",
        "Ector": "West Texas", "Tom Green": "West Texas", "Taylor": "West Texas",
        "Nolan": "West Texas", "Mitchell": "West Texas", "Howard": "West Texas",
        "Martin": "West Texas", "Andrews": "West Texas", "Winkler": "West Texas",
        "Ward": "West Texas", "Crane": "West Texas", "Upton": "West Texas",
        "Reagan": "West Texas", "Irion": "West Texas", "Sterling": "West Texas",
        "Coke": "West Texas", "Runnels": "West Texas", "Concho": "West Texas",
        "McCulloch": "West Texas", "San Saba": "West Texas", "Mason": "West Texas",
        "Llano": "West Texas", "Gillespie": "West Texas", "Blanco": "West Texas",
        "Kendall": "West Texas", "Comal": "West Texas", "Guadalupe": "West Texas",
        "Wilson": "West Texas", "Karnes": "West Texas", "DeWitt": "West Texas",
        "Victoria": "West Texas", "Goliad": "West Texas", "Refugio": "West Texas",
        "Aransas": "West Texas", "San Patricio": "West Texas", "Nueces": "West Texas",
        "Kleberg": "West Texas", "Kenedy": "West Texas", "Willacy": "West Texas",
        "Cameron": "West Texas", "Hidalgo": "West Texas", "Starr": "West Texas",
        "Jim Hogg": "West Texas", "Brooks": "West Texas", "Jim Wells": "West Texas",
        "Duval": "West Texas", "McMullen": "West Texas", "Live Oak": "West Texas",
        "Bee": "West Texas", "Atascosa": "West Texas", "Medina": "West Texas",
        "Uvalde": "West Texas", "Zavala": "West Texas", "Frio": "West Texas",
        "La Salle": "West Texas", "Dimmit": "West Texas", "Maverick": "West Texas",
        "Kinney": "West Texas", "Val Verde": "West Texas", "Edwards": "West Texas",
        "Real": "West Texas", "Bandera": "West Texas", "Kerr": "West Texas",
        "Kimble": "West Texas", "Menard": "West Texas", "Schleicher": "West Texas",
        "Sutton": "West Texas", "Crockett": "West Texas", "Terrell": "West Texas",
        "Pecos": "West Texas", "Brewster": "West Texas", "Presidio": "West Texas",
        "Jeff Davis": "West Texas", "Hudspeth": "West Texas", "Culberson": "West Texas",
        "Reeves": "West Texas", "Loving": "West Texas",
        "Lubbock": "Northwest Texas", "Potter": "Northwest Texas", "Randall": "Northwest Texas",
        "Hale": "Northwest Texas", "Lamb": "Northwest Texas", "Hockley": "Northwest Texas",
        "Terry": "Northwest Texas", "Yoakum": "Northwest Texas", "Gaines": "Northwest Texas",
        "Dawson": "Northwest Texas", "Borden": "Northwest Texas", "Scurry": "Northwest Texas",
        "Fisher": "Northwest Texas", "Jones": "Northwest Texas", "Shackelford": "Northwest Texas",
        "Stephens": "Northwest Texas", "Palo Pinto": "Northwest Texas", "Eastland": "Northwest Texas",
        "Callahan": "Northwest Texas", "Coleman": "Northwest Texas", "Brown": "Northwest Texas",
        "Comanche": "Northwest Texas", "Mills": "Northwest Texas", "Hamilton": "Northwest Texas",
        "Coryell": "Northwest Texas", "Lampasas": "Northwest Texas", "Burnet": "Northwest Texas",
    },
    "CA": {
        "Alameda": "California", "Contra Costa": "California", "Marin": "California",
        "San Francisco": "California", "San Mateo": "California",
        "Los Angeles": "Los Angeles", "Orange": "Los Angeles",
        "San Bernardino": "Los Angeles", "Santa Barbara": "Los Angeles", "Ventura": "Los Angeles",
        "Riverside": "Los Angeles",
        "San Diego": "San Diego", "Imperial": "San Diego",
        "Fresno": "San Joaquin", "Kern": "San Joaquin", "Kings": "San Joaquin",
        "Madera": "San Joaquin", "Mariposa": "San Joaquin", "Merced": "San Joaquin",
        "Stanislaus": "San Joaquin", "Tulare": "San Joaquin", "Tuolumne": "San Joaquin",
        "Del Norte": "Northern California", "Siskiyou": "Northern California",
        "Modoc": "Northern California", "Humboldt": "Northern California",
        "Trinity": "Northern California", "Shasta": "Northern California",
        "Lassen": "Northern California", "Tehama": "Northern California",
        "Plumas": "Northern California", "Butte": "Northern California",
        "Glenn": "Northern California", "Colusa": "Northern California",
        "Sutter": "Northern California", "Yuba": "Northern California",
        "Sierra": "Northern California", "Nevada": "Northern California",
        "Placer": "Northern California", "El Dorado": "Northern California",
        "Alpine": "Northern California", "Amador": "Northern California",
        "Calaveras": "Northern California", "Yolo": "Northern California",
        "Solano": "Northern California", "Napa": "Northern California",
        "Sonoma": "Northern California", "Mendocino": "Northern California",
        "Lake": "Northern California",
        "Monterey": "El Camino Real", "San Benito": "El Camino Real",
        "San Luis Obispo": "El Camino Real", "Santa Clara": "El Camino Real",
        "Santa Cruz": "El Camino Real",
    },
    "FL": {
        "Alachua": "Florida", "Baker": "Florida", "Bradford": "Florida",
        "Clay": "Florida", "Columbia": "Florida", "Dixie": "Florida",
        "Duval": "Florida", "Flagler": "Florida", "Gilchrist": "Florida",
        "Hamilton": "Florida", "Lafayette": "Florida", "Levy": "Florida",
        "Marion": "Florida", "Nassau": "Florida", "Putnam": "Florida",
        "St Johns": "Florida", "Suwannee": "Florida", "Taylor": "Florida",
        "Union": "Florida", "Volusia": "Florida",
        "Gadsden": "Florida", "Jefferson": "Florida", "Leon": "Florida",
        "Liberty": "Florida", "Madison": "Florida", "Wakulla": "Florida",
        "Broward": "Southeast Florida", "Miami-Dade": "Southeast Florida",
        "Monroe": "Southeast Florida", "Palm Beach": "Southeast Florida",
        "Charlotte": "Southwest Florida", "Collier": "Southwest Florida",
        "DeSoto": "Southwest Florida", "Glades": "Southwest Florida",
        "Hardee": "Southwest Florida", "Hendry": "Southwest Florida",
        "Hillsborough": "Southwest Florida", "Lee": "Southwest Florida",
        "Manatee": "Southwest Florida", "Pasco": "Southwest Florida",
        "Pinellas": "Southwest Florida", "Polk": "Southwest Florida",
        "Sarasota": "Southwest Florida",
        "Brevard": "Central Florida", "Citrus": "Central Florida",
        "Hernando": "Central Florida", "Indian River": "Central Florida",
        "Lake": "Central Florida", "Martin": "Central Florida",
        "Okeechobee": "Central Florida", "Orange": "Central Florida",
        "Osceola": "Central Florida", "St Lucie": "Central Florida",
        "Seminole": "Central Florida", "Sumter": "Central Florida",
        "Bay": "Central Gulf Coast", "Calhoun": "Central Gulf Coast",
        "Escambia": "Central Gulf Coast", "Franklin": "Central Gulf Coast",
        "Gulf": "Central Gulf Coast", "Holmes": "Central Gulf Coast",
        "Jackson": "Central Gulf Coast", "Okaloosa": "Central Gulf Coast",
        "Santa Rosa": "Central Gulf Coast", "Walton": "Central Gulf Coast",
        "Washington": "Central Gulf Coast",
    },
    "NY": {
        "Bronx": "New York", "New York": "New York", "Richmond": "New York",
        "Kings": "Long Island", "Queens": "Long Island", "Nassau": "Long Island",
        "Suffolk": "Long Island",
        "Albany": "Albany", "Columbia": "Albany", "Delaware": "Albany",
        "Fulton": "Albany", "Greene": "Albany", "Hamilton": "Albany",
        "Montgomery": "Albany", "Otsego": "Albany", "Rensselaer": "Albany",
        "Saratoga": "Albany", "Schenectady": "Albany", "Schoharie": "Albany",
        "Warren": "Albany", "Washington": "Albany",
        "Broome": "Central New York", "Cayuga": "Central New York",
        "Chemung": "Central New York", "Chenango": "Central New York",
        "Cortland": "Central New York", "Herkimer": "Central New York",
        "Jefferson": "Central New York", "Lewis": "Central New York",
        "Madison": "Central New York", "Oneida": "Central New York",
        "Onondaga": "Central New York", "Oswego": "Central New York",
        "Schuyler": "Central New York", "St Lawrence": "Central New York",
        "Tioga": "Central New York", "Tompkins": "Central New York",
        "Monroe": "Rochester", "Livingston": "Rochester", "Ontario": "Rochester",
        "Orleans": "Rochester", "Seneca": "Rochester", "Wayne": "Rochester",
        "Yates": "Rochester",
        "Allegany": "Western New York", "Cattaraugus": "Western New York",
        "Chautauqua": "Western New York", "Erie": "Western New York",
        "Genesee": "Western New York", "Niagara": "Western New York",
        "Wyoming": "Western New York",
        "Dutchess": "New York", "Orange": "New York", "Putnam": "New York",
        "Rockland": "New York", "Sullivan": "New York", "Ulster": "New York",
        "Westchester": "New York",
    },
    "NC": {
        "Alamance": "North Carolina", "Anson": "North Carolina", "Bertie": "North Carolina",
        "Bladen": "North Carolina", "Brunswick": "North Carolina", "Carteret": "North Carolina",
        "Caswell": "North Carolina", "Chatham": "North Carolina", "Columbus": "North Carolina",
        "Craven": "North Carolina", "Cumberland": "North Carolina", "Duplin": "North Carolina",
        "Durham": "North Carolina", "Edgecombe": "North Carolina", "Franklin": "North Carolina",
        "Granville": "North Carolina", "Greene": "North Carolina", "Guilford": "North Carolina",
        "Halifax": "North Carolina", "Harnett": "North Carolina", "Hoke": "North Carolina",
        "Johnston": "North Carolina", "Jones": "North Carolina", "Lee": "North Carolina",
        "Lenoir": "North Carolina", "Montgomery": "North Carolina", "Moore": "North Carolina",
        "Nash": "North Carolina", "New Hanover": "North Carolina", "Northampton": "North Carolina",
        "Onslow": "North Carolina", "Orange": "North Carolina", "Pamlico": "North Carolina",
        "Pender": "North Carolina", "Person": "North Carolina", "Pitt": "North Carolina",
        "Randolph": "North Carolina", "Richmond": "North Carolina", "Robeson": "North Carolina",
        "Rockingham": "North Carolina", "Sampson": "North Carolina", "Scotland": "North Carolina",
        "Stokes": "North Carolina", "Vance": "North Carolina", "Wake": "North Carolina",
        "Warren": "North Carolina", "Washington": "North Carolina", "Wayne": "North Carolina",
        "Wilson": "North Carolina",
        "Alleghany": "Western North Carolina", "Ashe": "Western North Carolina",
        "Avery": "Western North Carolina", "Buncombe": "Western North Carolina",
        "Burke": "Western North Carolina", "Caldwell": "Western North Carolina",
        "Cherokee": "Western North Carolina", "Clay": "Western North Carolina",
        "Cleveland": "Western North Carolina", "Gaston": "Western North Carolina",
        "Graham": "Western North Carolina", "Haywood": "Western North Carolina",
        "Henderson": "Western North Carolina", "Jackson": "Western North Carolina",
        "Lincoln": "Western North Carolina", "Macon": "Western North Carolina",
        "Madison": "Western North Carolina", "McDowell": "Western North Carolina",
        "Mitchell": "Western North Carolina", "Polk": "Western North Carolina",
        "Rutherford": "Western North Carolina", "Swain": "Western North Carolina",
        "Transylvania": "Western North Carolina", "Watauga": "Western North Carolina",
        "Wilkes": "Western North Carolina", "Yancey": "Western North Carolina",
        "Beaufort": "East Carolina", "Camden": "East Carolina", "Chowan": "East Carolina",
        "Currituck": "East Carolina", "Dare": "East Carolina", "Gates": "East Carolina",
        "Hertford": "East Carolina", "Hyde": "East Carolina", "Martin": "East Carolina",
        "Pasquotank": "East Carolina", "Perquimans": "East Carolina", "Tyrrell": "East Carolina",
    },
    "LA": {
        "Ascension": "Louisiana", "Assumption": "Louisiana", "East Baton Rouge": "Louisiana",
        "East Feliciana": "Louisiana", "Iberville": "Louisiana", "Jefferson": "Louisiana",
        "Livingston": "Louisiana", "Orleans": "Louisiana", "Plaquemines": "Louisiana",
        "St Bernard": "Louisiana", "St Charles": "Louisiana", "St Helena": "Louisiana",
        "St James": "Louisiana", "St John the Baptist": "Louisiana", "St Tammany": "Louisiana",
        "Tangipahoa": "Louisiana", "Washington": "Louisiana", "West Baton Rouge": "Louisiana",
        "West Feliciana": "Louisiana",
        "Acadia": "Western Louisiana", "Allen": "Western Louisiana", "Avoyelles": "Western Louisiana",
        "Beauregard": "Western Louisiana", "Bienville": "Western Louisiana", "Bossier": "Western Louisiana",
        "Caddo": "Western Louisiana", "Calcasieu": "Western Louisiana", "Caldwell": "Western Louisiana",
        "Cameron": "Western Louisiana", "Catahoula": "Western Louisiana", "Claiborne": "Western Louisiana",
        "Concordia": "Western Louisiana", "De Soto": "Western Louisiana", "East Carroll": "Western Louisiana",
        "Evangeline": "Western Louisiana", "Franklin": "Western Louisiana", "Grant": "Western Louisiana",
        "Iberia": "Western Louisiana", "Jackson": "Western Louisiana", "Jefferson Davis": "Western Louisiana",
        "La Salle": "Western Louisiana", "Lafayette": "Western Louisiana", "Lafourche": "Western Louisiana",
        "Lincoln": "Western Louisiana", "Madison": "Western Louisiana", "Morehouse": "Western Louisiana",
        "Natchitoches": "Western Louisiana", "Ouachita": "Western Louisiana", "Pointe Coupee": "Western Louisiana",
        "Rapides": "Western Louisiana", "Red River": "Western Louisiana", "Richland": "Western Louisiana",
        "Sabine": "Western Louisiana", "St Landry": "Western Louisiana", "St Martin": "Western Louisiana",
        "St Mary": "Western Louisiana", "Tensas": "Western Louisiana", "Terrebonne": "Western Louisiana",
        "Union": "Western Louisiana", "Vermilion": "Western Louisiana", "Vernon": "Western Louisiana",
        "Webster": "Western Louisiana", "West Carroll": "Western Louisiana", "Winn": "Western Louisiana",
    },
    "GA": {
        "Appling": "Georgia", "Atkinson": "Georgia", "Bacon": "Georgia", "Baker": "Georgia",
        "Ben Hill": "Georgia", "Berrien": "Georgia", "Brantley": "Georgia", "Brooks": "Georgia",
        "Bryan": "Georgia", "Bulloch": "Georgia", "Burke": "Georgia", "Calhoun": "Georgia",
        "Camden": "Georgia", "Candler": "Georgia", "Charlton": "Georgia", "Chatham": "Georgia",
        "Clinch": "Georgia", "Coffee": "Georgia", "Colquitt": "Georgia", "Columbia": "Georgia",
        "Cook": "Georgia", "Decatur": "Georgia", "Dodge": "Georgia", "Dougherty": "Georgia",
        "Early": "Georgia", "Echols": "Georgia", "Effingham": "Georgia", "Emanuel": "Georgia",
        "Evans": "Georgia", "Glascock": "Georgia", "Glynn": "Georgia", "Grady": "Georgia",
        "Irwin": "Georgia", "Jeff Davis": "Georgia", "Jefferson": "Georgia", "Jenkins": "Georgia",
        "Johnson": "Georgia", "Lanier": "Georgia", "Laurens": "Georgia", "Lee": "Georgia",
        "Liberty": "Georgia", "Lincoln": "Georgia", "Long": "Georgia", "Lowndes": "Georgia",
        "McDuffie": "Georgia", "McIntosh": "Georgia", "Miller": "Georgia", "Mitchell": "Georgia",
        "Montgomery": "Georgia", "Pierce": "Georgia", "Pulaski": "Georgia", "Richmond": "Georgia",
        "Screven": "Georgia", "Seminole": "Georgia", "Tattnall": "Georgia", "Telfair": "Georgia",
        "Thomas": "Georgia", "Tift": "Georgia", "Toombs": "Georgia", "Treutlen": "Georgia",
        "Turner": "Georgia", "Ware": "Georgia", "Warren": "Georgia", "Washington": "Georgia",
        "Wayne": "Georgia", "Wheeler": "Georgia", "Wilcox": "Georgia", "Wilkinson": "Georgia",
        "Worth": "Georgia",
        "Baldwin": "Atlanta", "Banks": "Atlanta", "Barrow": "Atlanta", "Bartow": "Atlanta",
        "Bibb": "Atlanta", "Bleckley": "Atlanta", "Butts": "Atlanta", "Carroll": "Atlanta",
        "Catoosa": "Atlanta", "Chattahoochee": "Atlanta", "Chattooga": "Atlanta",
        "Cherokee": "Atlanta", "Clarke": "Atlanta", "Clay": "Atlanta", "Clayton": "Atlanta",
        "Cobb": "Atlanta", "Coweta": "Atlanta", "Crawford": "Atlanta", "Crisp": "Atlanta",
        "Dade": "Atlanta", "Dawson": "Atlanta", "DeKalb": "Atlanta", "Dooly": "Atlanta",
        "Douglas": "Atlanta", "Elbert": "Atlanta", "Fannin": "Atlanta", "Fayette": "Atlanta",
        "Floyd": "Atlanta", "Forsyth": "Atlanta", "Franklin": "Atlanta", "Fulton": "Atlanta",
        "Gilmer": "Atlanta", "Gordon": "Atlanta", "Greene": "Atlanta", "Gwinnett": "Atlanta",
        "Habersham": "Atlanta", "Hall": "Atlanta", "Hancock": "Atlanta", "Haralson": "Atlanta",
        "Harris": "Atlanta", "Hart": "Atlanta", "Heard": "Atlanta", "Henry": "Atlanta",
        "Houston": "Atlanta", "Jackson": "Atlanta", "Jasper": "Atlanta", "Jones": "Atlanta",
        "Lamar": "Atlanta", "Lumpkin": "Atlanta", "Macon": "Atlanta", "Madison": "Atlanta",
        "Marion": "Atlanta", "Meriwether": "Atlanta", "Monroe": "Atlanta", "Morgan": "Atlanta",
        "Murray": "Atlanta", "Muscogee": "Atlanta", "Newton": "Atlanta", "Oconee": "Atlanta",
        "Oglethorpe": "Atlanta", "Paulding": "Atlanta", "Peach": "Atlanta", "Pickens": "Atlanta",
        "Pike": "Atlanta", "Polk": "Atlanta", "Putnam": "Atlanta", "Quitman": "Atlanta",
        "Rabun": "Atlanta", "Randolph": "Atlanta", "Rockdale": "Atlanta", "Schley": "Atlanta",
        "Spalding": "Atlanta", "Stephens": "Atlanta", "Stewart": "Atlanta", "Sumter": "Atlanta",
        "Talbot": "Atlanta", "Taliaferro": "Atlanta", "Taylor": "Atlanta", "Terrell": "Atlanta",
        "Towns": "Atlanta", "Troup": "Atlanta", "Twiggs": "Atlanta", "Union": "Atlanta",
        "Upson": "Atlanta", "Walker": "Atlanta", "Walton": "Atlanta", "Webster": "Atlanta",
        "White": "Atlanta", "Whitfield": "Atlanta",
    },
    "PA": {
        "Philadelphia": "Pennsylvania", "Bucks": "Pennsylvania", "Chester": "Pennsylvania",
        "Delaware": "Pennsylvania", "Montgomery": "Pennsylvania",
        "Allegheny": "Pittsburgh", "Armstrong": "Pittsburgh", "Beaver": "Pittsburgh",
        "Butler": "Pittsburgh", "Cambria": "Pittsburgh", "Fayette": "Pittsburgh",
        "Greene": "Pittsburgh", "Indiana": "Pittsburgh", "Somerset": "Pittsburgh",
        "Washington": "Pittsburgh", "Westmoreland": "Pittsburgh",
        "Crawford": "Northwestern Pennsylvania", "Erie": "Northwestern Pennsylvania",
        "Mercer": "Northwestern Pennsylvania", "Venango": "Northwestern Pennsylvania",
        "Warren": "Northwestern Pennsylvania",
        "Adams": "Susquehanna", "Bedford": "Susquehanna", "Berks": "Susquehanna",
        "Blair": "Susquehanna", "Bradford": "Susquehanna", "Carbon": "Susquehanna",
        "Centre": "Susquehanna", "Clarion": "Susquehanna", "Clearfield": "Susquehanna",
        "Clinton": "Susquehanna", "Columbia": "Susquehanna", "Cumberland": "Susquehanna",
        "Dauphin": "Susquehanna", "Elk": "Susquehanna", "Forest": "Susquehanna",
        "Franklin": "Susquehanna", "Fulton": "Susquehanna", "Huntingdon": "Susquehanna",
        "Jefferson": "Susquehanna", "Juniata": "Susquehanna", "Lackawanna": "Susquehanna",
        "Lancaster": "Susquehanna", "Lawrence": "Susquehanna", "Lebanon": "Susquehanna",
        "Lehigh": "Susquehanna", "Luzerne": "Susquehanna", "Lycoming": "Susquehanna",
        "McKean": "Susquehanna", "Mifflin": "Susquehanna", "Monroe": "Susquehanna",
        "Montour": "Susquehanna", "Northampton": "Susquehanna", "Northumberland": "Susquehanna",
        "Perry": "Susquehanna", "Pike": "Susquehanna", "Potter": "Susquehanna",
        "Schuylkill": "Susquehanna", "Snyder": "Susquehanna", "Sullivan": "Susquehanna",
        "Susquehanna": "Susquehanna", "Tioga": "Susquehanna", "Union": "Susquehanna",
        "Wayne": "Susquehanna", "Wyoming": "Susquehanna", "York": "Susquehanna",
    },
    "MO": {
        "Adair": "Missouri", "Audrain": "Missouri", "Boone": "Missouri",
        "Callaway": "Missouri", "Clark": "Missouri", "Franklin": "Missouri",
        "Gasconade": "Missouri", "Jefferson": "Missouri", "Knox": "Missouri",
        "Lewis": "Missouri", "Lincoln": "Missouri", "Macon": "Missouri",
        "Marion": "Missouri", "Montgomery": "Missouri", "Pike": "Missouri",
        "Ralls": "Missouri", "St Charles": "Missouri", "St Louis": "Missouri",
        "Shelby": "Missouri", "Warren": "Missouri", "Washington": "Missouri",
        "Andrew": "West Missouri", "Atchison": "West Missouri", "Barry": "West Missouri",
        "Barton": "West Missouri", "Bates": "West Missouri", "Benton": "West Missouri",
        "Buchanan": "West Missouri", "Caldwell": "West Missouri", "Camden": "West Missouri",
        "Cape Girardeau": "West Missouri", "Carroll": "West Missouri", "Cass": "West Missouri",
        "Cedar": "West Missouri", "Chariton": "West Missouri", "Christian": "West Missouri",
        "Clay": "West Missouri", "Clinton": "West Missouri", "Cole": "West Missouri",
        "Cooper": "West Missouri", "Dade": "West Missouri", "Dallas": "West Missouri",
        "Daviess": "West Missouri", "DeKalb": "West Missouri", "Dent": "West Missouri",
        "Douglas": "West Missouri", "Dunklin": "West Missouri", "Gentry": "West Missouri",
        "Greene": "West Missouri", "Grundy": "West Missouri", "Harrison": "West Missouri",
        "Henry": "West Missouri", "Hickory": "West Missouri", "Holt": "West Missouri",
        "Howard": "West Missouri", "Howell": "West Missouri", "Iron": "West Missouri",
        "Jackson": "West Missouri", "Jasper": "West Missouri", "Johnson": "West Missouri",
        "Laclede": "West Missouri", "Lafayette": "West Missouri", "Lawrence": "West Missouri",
        "Livingston": "West Missouri", "Madison": "West Missouri", "McDonald": "West Missouri",
        "Mercer": "West Missouri", "Miller": "West Missouri", "Mississippi": "West Missouri",
        "Moniteau": "West Missouri", "Monroe": "West Missouri", "Morgan": "West Missouri",
        "New Madrid": "West Missouri", "Newton": "West Missouri", "Nodaway": "West Missouri",
        "Oregon": "West Missouri", "Osage": "West Missouri", "Ozark": "West Missouri",
        "Pemiscot": "West Missouri", "Perry": "West Missouri", "Pettis": "West Missouri",
        "Phelps": "West Missouri", "Platte": "West Missouri", "Polk": "West Missouri",
        "Pulaski": "West Missouri", "Putnam": "West Missouri", "Randolph": "West Missouri",
        "Ray": "West Missouri", "Reynolds": "West Missouri", "Ripley": "West Missouri",
        "Saline": "West Missouri", "Schuyler": "West Missouri", "Scotland": "West Missouri",
        "Scott": "West Missouri", "Shannon": "West Missouri", "St Clair": "West Missouri",
        "St Francois": "West Missouri", "Ste Genevieve": "West Missouri", "Stoddard": "West Missouri",
        "Stone": "West Missouri", "Sullivan": "West Missouri", "Taney": "West Missouri",
        "Texas": "West Missouri", "Vernon": "West Missouri", "Wayne": "West Missouri",
        "Webster": "West Missouri", "Worth": "West Missouri", "Wright": "West Missouri",
    },
    "OH": {
        "Ashland": "Ohio", "Ashtabula": "Ohio", "Carroll": "Ohio", "Columbiana": "Ohio",
        "Cuyahoga": "Ohio", "Erie": "Ohio", "Geauga": "Ohio", "Holmes": "Ohio",
        "Huron": "Ohio", "Lake": "Ohio", "Lorain": "Ohio", "Mahoning": "Ohio",
        "Medina": "Ohio", "Portage": "Ohio", "Richland": "Ohio", "Stark": "Ohio",
        "Summit": "Ohio", "Trumbull": "Ohio", "Tuscarawas": "Ohio", "Wayne": "Ohio",
        "Adams": "Southern Ohio", "Allen": "Southern Ohio", "Athens": "Southern Ohio",
        "Auglaize": "Southern Ohio", "Belmont": "Southern Ohio", "Brown": "Southern Ohio",
        "Butler": "Southern Ohio", "Champaign": "Southern Ohio", "Clark": "Southern Ohio",
        "Clermont": "Southern Ohio", "Clinton": "Southern Ohio", "Coshocton": "Southern Ohio",
        "Crawford": "Southern Ohio", "Darke": "Southern Ohio", "Defiance": "Southern Ohio",
        "Delaware": "Southern Ohio", "Fairfield": "Southern Ohio", "Fayette": "Southern Ohio",
        "Franklin": "Southern Ohio", "Fulton": "Southern Ohio", "Gallia": "Southern Ohio",
        "Greene": "Southern Ohio", "Guernsey": "Southern Ohio", "Hamilton": "Southern Ohio",
        "Hancock": "Southern Ohio", "Hardin": "Southern Ohio", "Harrison": "Southern Ohio",
        "Henry": "Southern Ohio", "Highland": "Southern Ohio", "Hocking": "Southern Ohio",
        "Jackson": "Southern Ohio", "Jefferson": "Southern Ohio", "Knox": "Southern Ohio",
        "Lawrence": "Southern Ohio", "Licking": "Southern Ohio", "Logan": "Southern Ohio",
        "Lucas": "Southern Ohio", "Madison": "Southern Ohio", "Marion": "Southern Ohio",
        "Meigs": "Southern Ohio", "Mercer": "Southern Ohio", "Miami": "Southern Ohio",
        "Monroe": "Southern Ohio", "Montgomery": "Southern Ohio", "Morgan": "Southern Ohio",
        "Morrow": "Southern Ohio", "Muskingum": "Southern Ohio", "Noble": "Southern Ohio",
        "Ottawa": "Southern Ohio", "Paulding": "Southern Ohio", "Perry": "Southern Ohio",
        "Pickaway": "Southern Ohio", "Pike": "Southern Ohio", "Preble": "Southern Ohio",
        "Putnam": "Southern Ohio", "Ross": "Southern Ohio", "Sandusky": "Southern Ohio",
        "Scioto": "Southern Ohio", "Seneca": "Southern Ohio", "Shelby": "Southern Ohio",
        "Union": "Southern Ohio", "Van Wert": "Southern Ohio", "Vinton": "Southern Ohio",
        "Warren": "Southern Ohio", "Washington": "Southern Ohio", "Williams": "Southern Ohio",
        "Wood": "Southern Ohio", "Wyandot": "Southern Ohio",
    },
    "MI": {
        "Alcona": "Michigan", "Alger": "Michigan", "Allegan": "Michigan", "Alpena": "Michigan",
        "Antrim": "Michigan", "Arenac": "Michigan", "Barry": "Michigan", "Bay": "Michigan",
        "Benzie": "Michigan", "Berrien": "Michigan", "Branch": "Michigan", "Calhoun": "Michigan",
        "Cass": "Michigan", "Charlevoix": "Michigan", "Cheboygan": "Michigan",
        "Clare": "Michigan", "Clinton": "Michigan", "Crawford": "Michigan", "Delta": "Michigan",
        "Eaton": "Michigan", "Emmet": "Michigan", "Genesee": "Michigan", "Gladwin": "Michigan",
        "Grand Traverse": "Michigan", "Gratiot": "Michigan", "Hillsdale": "Michigan",
        "Huron": "Michigan", "Ingham": "Michigan", "Ionia": "Michigan", "Iosco": "Michigan",
        "Isabella": "Michigan", "Jackson": "Michigan", "Kalamazoo": "Michigan",
        "Kalkaska": "Michigan", "Kent": "Michigan", "Lake": "Michigan", "Lapeer": "Michigan",
        "Leelanau": "Michigan", "Lenawee": "Michigan", "Livingston": "Michigan",
        "Mackinac": "Michigan", "Macomb": "Michigan", "Manistee": "Michigan",
        "Mason": "Michigan", "Mecosta": "Michigan", "Menominee": "Michigan",
        "Midland": "Michigan", "Missaukee": "Michigan", "Monroe": "Michigan",
        "Montcalm": "Michigan", "Montmorency": "Michigan", "Muskegon": "Michigan",
        "Newaygo": "Michigan", "Oakland": "Michigan", "Oceana": "Michigan",
        "Ogemaw": "Michigan", "Osceola": "Michigan", "Oscoda": "Michigan",
        "Otsego": "Michigan", "Ottawa": "Michigan", "Presque Isle": "Michigan",
        "Roscommon": "Michigan", "Saginaw": "Michigan", "Sanilac": "Michigan",
        "Shiawassee": "Michigan", "St Clair": "Michigan", "St Joseph": "Michigan",
        "Tuscola": "Michigan", "Van Buren": "Michigan", "Washtenaw": "Michigan",
        "Wayne": "Michigan", "Wexford": "Michigan",
    },
    "IL": {
        "Cook": "Chicago", "DuPage": "Chicago", "Grundy": "Chicago", "Kane": "Chicago",
        "Kankakee": "Chicago", "Kendall": "Chicago", "Lake": "Chicago", "McHenry": "Chicago",
        "Will": "Chicago",
        "Adams": "Springfield", "Alexander": "Springfield", "Bond": "Springfield",
        "Boone": "Springfield", "Brown": "Springfield", "Bureau": "Springfield",
        "Calhoun": "Springfield", "Carroll": "Springfield", "Cass": "Springfield",
        "Champaign": "Springfield", "Christian": "Springfield", "Clark": "Springfield",
        "Clay": "Springfield", "Clinton": "Springfield", "Coles": "Springfield",
        "Crawford": "Springfield", "Cumberland": "Springfield", "DeKalb": "Springfield",
        "DeWitt": "Springfield", "Douglas": "Springfield", "Edgar": "Springfield",
        "Edwards": "Springfield", "Effingham": "Springfield", "Fayette": "Springfield",
        "Ford": "Springfield", "Franklin": "Springfield", "Fulton": "Springfield",
        "Gallatin": "Springfield", "Greene": "Springfield", "Hamilton": "Springfield",
        "Hancock": "Springfield", "Hardin": "Springfield", "Henderson": "Springfield",
        "Henry": "Springfield", "Iroquois": "Springfield", "Jackson": "Springfield",
        "Jasper": "Springfield", "Jefferson": "Springfield", "Jersey": "Springfield",
        "Jo Daviess": "Springfield", "Johnson": "Springfield", "Knox": "Springfield",
        "LaSalle": "Springfield", "Lawrence": "Springfield", "Lee": "Springfield",
        "Livingston": "Springfield", "Logan": "Springfield", "Macon": "Springfield",
        "Macoupin": "Springfield", "Madison": "Springfield", "Marion": "Springfield",
        "Marshall": "Springfield", "Mason": "Springfield", "Massac": "Springfield",
        "McDonough": "Springfield", "McLean": "Springfield", "Menard": "Springfield",
        "Mercer": "Springfield", "Monroe": "Springfield", "Montgomery": "Springfield",
        "Morgan": "Springfield", "Moultrie": "Springfield", "Ogle": "Springfield",
        "Peoria": "Springfield", "Perry": "Springfield", "Piatt": "Springfield",
        "Pike": "Springfield", "Pope": "Springfield", "Pulaski": "Springfield",
        "Putnam": "Springfield", "Randolph": "Springfield", "Richland": "Springfield",
        "Rock Island": "Springfield", "Saline": "Springfield", "Sangamon": "Springfield",
        "Schuyler": "Springfield", "Scott": "Springfield", "Shelby": "Springfield",
        "St Clair": "Springfield", "Stark": "Springfield", "Stephenson": "Springfield",
        "Tazewell": "Springfield", "Union": "Springfield", "Vermilion": "Springfield",
        "Wabash": "Springfield", "Warren": "Springfield", "Washington": "Springfield",
        "Wayne": "Springfield", "White": "Springfield", "Whiteside": "Springfield",
        "Williamson": "Springfield", "Winnebago": "Springfield", "Woodford": "Springfield",
    },
    "VA": {
        "Alexandria": "Virginia", "Arlington": "Virginia", "Caroline": "Virginia",
        "Culpeper": "Virginia", "Fairfax": "Virginia", "Fauquier": "Virginia",
        "King George": "Virginia", "Loudoun": "Virginia", "Louisa": "Virginia",
        "Orange": "Virginia", "Prince William": "Virginia", "Rappahannock": "Virginia",
        "Spotsylvania": "Virginia", "Stafford": "Virginia",
        "Albemarle": "Virginia", "Augusta": "Virginia", "Clarke": "Virginia",
        "Frederick": "Virginia", "Greene": "Virginia", "Highland": "Virginia",
        "Madison": "Virginia", "Page": "Virginia", "Rockingham": "Virginia",
        "Shenandoah": "Virginia", "Warren": "Virginia",
        "Accomack": "Southern Virginia", "Amelia": "Southern Virginia",
        "Brunswick": "Southern Virginia", "Charles City": "Southern Virginia",
        "Chesterfield": "Southern Virginia", "Dinwiddie": "Southern Virginia",
        "Essex": "Southern Virginia", "Franklin": "Southern Virginia",
        "Gloucester": "Southern Virginia", "Greensville": "Southern Virginia",
        "Henrico": "Southern Virginia", "Isle of Wight": "Southern Virginia",
        "James City": "Southern Virginia", "King and Queen": "Southern Virginia",
        "King William": "Southern Virginia", "Lancaster": "Southern Virginia",
        "Mathews": "Southern Virginia", "Middlesex": "Southern Virginia",
        "New Kent": "Southern Virginia", "Northampton": "Southern Virginia",
        "Nottoway": "Southern Virginia", "Powhatan": "Southern Virginia",
        "Prince George": "Southern Virginia", "Richmond": "Southern Virginia",
        "Southampton": "Southern Virginia", "Surry": "Southern Virginia",
        "Sussex": "Southern Virginia", "Westmoreland": "Southern Virginia",
        "York": "Southern Virginia",
        "Alleghany": "Southwestern Virginia", "Bedford": "Southwestern Virginia",
        "Bland": "Southwestern Virginia", "Botetourt": "Southwestern Virginia",
        "Buchanan": "Southwestern Virginia", "Carroll": "Southwestern Virginia",
        "Craig": "Southwestern Virginia", "Dickenson": "Southwestern Virginia",
        "Floyd": "Southwestern Virginia", "Giles": "Southwestern Virginia",
        "Grayson": "Southwestern Virginia", "Lee": "Southwestern Virginia",
        "Montgomery": "Southwestern Virginia", "Patrick": "Southwestern Virginia",
        "Pulaski": "Southwestern Virginia", "Roanoke": "Southwestern Virginia",
        "Russell": "Southwestern Virginia", "Scott": "Southwestern Virginia",
        "Smyth": "Southwestern Virginia", "Tazewell": "Southwestern Virginia",
        "Washington": "Southwestern Virginia", "Wise": "Southwestern Virginia",
        "Wythe": "Southwestern Virginia",
    },
    "SC": {
        "Abbeville": "Upper South Carolina", "Aiken": "Upper South Carolina",
        "Allendale": "South Carolina", "Anderson": "Upper South Carolina",
        "Bamberg": "South Carolina", "Barnwell": "South Carolina",
        "Beaufort": "South Carolina", "Berkeley": "South Carolina",
        "Calhoun": "South Carolina", "Charleston": "South Carolina",
        "Cherokee": "Upper South Carolina", "Chester": "Upper South Carolina",
        "Chesterfield": "Upper South Carolina", "Clarendon": "South Carolina",
        "Colleton": "South Carolina", "Darlington": "South Carolina",
        "Dillon": "South Carolina", "Dorchester": "South Carolina",
        "Edgefield": "Upper South Carolina", "Fairfield": "Upper South Carolina",
        "Florence": "South Carolina", "Georgetown": "South Carolina",
        "Greenville": "Upper South Carolina", "Greenwood": "Upper South Carolina",
        "Hampton": "South Carolina", "Horry": "South Carolina",
        "Jasper": "South Carolina", "Kershaw": "Upper South Carolina",
        "Lancaster": "Upper South Carolina", "Laurens": "Upper South Carolina",
        "Lee": "South Carolina", "Lexington": "Upper South Carolina",
        "Marion": "South Carolina", "Marlboro": "South Carolina",
        "McCormick": "Upper South Carolina", "Newberry": "Upper South Carolina",
        "Oconee": "Upper South Carolina", "Orangeburg": "South Carolina",
        "Pickens": "Upper South Carolina", "Richland": "Upper South Carolina",
        "Saluda": "Upper South Carolina", "Spartanburg": "Upper South Carolina",
        "Sumter": "South Carolina", "Union": "Upper South Carolina",
        "Williamsburg": "South Carolina", "York": "Upper South Carolina",
    },
    "TN": {
        "Anderson": "Tennessee", "Bedford": "Tennessee", "Bledsoe": "Tennessee",
        "Blount": "Tennessee", "Campbell": "Tennessee", "Cannon": "Tennessee",
        "Cheatham": "Tennessee", "Chester": "Tennessee", "Claiborne": "Tennessee",
        "Clay": "Tennessee", "Cumberland": "Tennessee", "Davidson": "Tennessee",
        "Decatur": "Tennessee", "DeKalb": "Tennessee", "Dickson": "Tennessee",
        "Fayette": "Tennessee", "Fentress": "Tennessee", "Franklin": "Tennessee",
        "Gibson": "Tennessee", "Giles": "Tennessee", "Grainger": "Tennessee",
        "Grundy": "Tennessee", "Hardeman": "Tennessee", "Hardin": "Tennessee",
        "Haywood": "Tennessee", "Henderson": "Tennessee", "Henry": "Tennessee",
        "Hickman": "Tennessee", "Houston": "Tennessee", "Humphreys": "Tennessee",
        "Jackson": "Tennessee", "Lauderdale": "Tennessee", "Lawrence": "Tennessee",
        "Lewis": "Tennessee", "Lincoln": "Tennessee", "Macon": "Tennessee",
        "Madison": "Tennessee", "Marion": "Tennessee", "Marshall": "Tennessee",
        "Maury": "Tennessee", "McMinn": "Tennessee", "McNairy": "Tennessee",
        "Meigs": "Tennessee", "Monroe": "Tennessee", "Montgomery": "Tennessee",
        "Moore": "Tennessee", "Morgan": "Tennessee", "Obion": "Tennessee",
        "Overton": "Tennessee", "Perry": "Tennessee", "Pickett": "Tennessee",
        "Polk": "Tennessee", "Putnam": "Tennessee", "Rhea": "Tennessee",
        "Roane": "Tennessee", "Robertson": "Tennessee", "Rutherford": "Tennessee",
        "Scott": "Tennessee", "Sequatchie": "Tennessee", "Shelby": "Tennessee",
        "Smith": "Tennessee", "Stewart": "Tennessee", "Sumner": "Tennessee",
        "Tipton": "Tennessee", "Trousdale": "Tennessee", "Van Buren": "Tennessee",
        "Warren": "Tennessee", "Wayne": "Tennessee", "Weakley": "Tennessee",
        "White": "Tennessee", "Williamson": "Tennessee", "Wilson": "Tennessee",
        "Carter": "East Tennessee", "Cocke": "East Tennessee", "Greene": "East Tennessee",
        "Hamblen": "East Tennessee", "Hancock": "East Tennessee", "Hawkins": "East Tennessee",
        "Jefferson": "East Tennessee", "Johnson": "East Tennessee", "Knox": "East Tennessee",
        "Loudon": "East Tennessee", "Sevier": "East Tennessee", "Sullivan": "East Tennessee",
        "Unicoi": "East Tennessee", "Union": "East Tennessee", "Washington": "East Tennessee",
        "Benton": "West Tennessee", "Carroll": "West Tennessee", "Crockett": "West Tennessee",
        "Dyer": "West Tennessee", "Lake": "West Tennessee",
    },
    "WA": {
        "Clallam": "Olympia", "Clark": "Olympia", "Cowlitz": "Olympia",
        "Grays Harbor": "Olympia", "Island": "Olympia", "Jefferson": "Olympia",
        "King": "Olympia", "Kitsap": "Olympia", "Lewis": "Olympia",
        "Mason": "Olympia", "Pacific": "Olympia", "Pierce": "Olympia",
        "San Juan": "Olympia", "Skagit": "Olympia", "Snohomish": "Olympia",
        "Thurston": "Olympia", "Wahkiakum": "Olympia", "Whatcom": "Olympia",
        "Adams": "Spokane", "Asotin": "Spokane", "Benton": "Spokane",
        "Chelan": "Spokane", "Columbia": "Spokane", "Douglas": "Spokane",
        "Ferry": "Spokane", "Franklin": "Spokane", "Garfield": "Spokane",
        "Grant": "Spokane", "Kittitas": "Spokane", "Klickitat": "Spokane",
        "Lincoln": "Spokane", "Okanogan": "Spokane", "Pend Oreille": "Spokane",
        "Stevens": "Spokane", "Walla Walla": "Spokane", "Whitman": "Spokane",
        "Yakima": "Spokane",
    },
    "OR": {
        "Baker": "Eastern Oregon", "Crook": "Eastern Oregon", "Deschutes": "Eastern Oregon",
        "Gilliam": "Eastern Oregon", "Grant": "Eastern Oregon", "Harney": "Eastern Oregon",
        "Hood River": "Eastern Oregon", "Jefferson": "Eastern Oregon", "Klamath": "Eastern Oregon",
        "Lake": "Eastern Oregon", "Malheur": "Eastern Oregon", "Morrow": "Eastern Oregon",
        "Sherman": "Eastern Oregon", "Umatilla": "Eastern Oregon", "Union": "Eastern Oregon",
        "Wallowa": "Eastern Oregon", "Wasco": "Eastern Oregon", "Wheeler": "Eastern Oregon",
        "Benton": "Oregon", "Clackamas": "Oregon", "Clatsop": "Oregon", "Columbia": "Oregon",
        "Coos": "Oregon", "Curry": "Oregon", "Douglas": "Oregon", "Jackson": "Oregon",
        "Josephine": "Oregon", "Lane": "Oregon", "Lincoln": "Oregon", "Linn": "Oregon",
        "Marion": "Oregon", "Multnomah": "Oregon", "Polk": "Oregon", "Tillamook": "Oregon",
        "Washington": "Oregon", "Yamhill": "Oregon",
    },
    "KS": {
        "Allen": "Kansas", "Anderson": "Kansas", "Atchison": "Kansas", "Bourbon": "Kansas",
        "Brown": "Kansas", "Chase": "Kansas", "Chautauqua": "Kansas", "Cherokee": "Kansas",
        "Clay": "Kansas", "Coffey": "Kansas", "Cowley": "Kansas", "Crawford": "Kansas",
        "Dickinson": "Kansas", "Doniphan": "Kansas", "Douglas": "Kansas", "Elk": "Kansas",
        "Franklin": "Kansas", "Geary": "Kansas", "Greenwood": "Kansas", "Harper": "Kansas",
        "Jackson": "Kansas", "Jefferson": "Kansas", "Johnson": "Kansas", "Labette": "Kansas",
        "Leavenworth": "Kansas", "Linn": "Kansas", "Lyon": "Kansas", "Marion": "Kansas",
        "Marshall": "Kansas", "Miami": "Kansas", "Montgomery": "Kansas", "Morris": "Kansas",
        "Nemaha": "Kansas", "Neosho": "Kansas", "Osage": "Kansas", "Pottawatomie": "Kansas",
        "Riley": "Kansas", "Sedgwick": "Kansas", "Shawnee": "Kansas", "Sumner": "Kansas",
        "Wabaunsee": "Kansas", "Washington": "Kansas", "Wilson": "Kansas", "Woodson": "Kansas",
        "Wyandotte": "Kansas",
        "Barber": "Western Kansas", "Barton": "Western Kansas", "Butler": "Western Kansas",
        "Cheyenne": "Western Kansas", "Clark": "Western Kansas", "Cloud": "Western Kansas",
        "Comanche": "Western Kansas", "Decatur": "Western Kansas", "Edwards": "Western Kansas",
        "Ellis": "Western Kansas", "Ellsworth": "Western Kansas", "Finney": "Western Kansas",
        "Ford": "Western Kansas", "Gove": "Western Kansas", "Graham": "Western Kansas",
        "Grant": "Western Kansas", "Gray": "Western Kansas", "Greeley": "Western Kansas",
        "Hamilton": "Western Kansas", "Harvey": "Western Kansas", "Haskell": "Western Kansas",
        "Hodgeman": "Western Kansas", "Jewell": "Western Kansas", "Kearny": "Western Kansas",
        "Kingman": "Western Kansas", "Kiowa": "Western Kansas", "Lane": "Western Kansas",
        "Lincoln": "Western Kansas", "Logan": "Western Kansas", "McPherson": "Western Kansas",
        "Meade": "Western Kansas", "Mitchell": "Western Kansas", "Morton": "Western Kansas",
        "Ness": "Western Kansas", "Norton": "Western Kansas", "Osborne": "Western Kansas",
        "Ottawa": "Western Kansas", "Pawnee": "Western Kansas", "Phillips": "Western Kansas",
        "Pratt": "Western Kansas", "Rawlins": "Western Kansas", "Reno": "Western Kansas",
        "Republic": "Western Kansas", "Rice": "Western Kansas", "Rooks": "Western Kansas",
        "Rush": "Western Kansas", "Russell": "Western Kansas", "Saline": "Western Kansas",
        "Scott": "Western Kansas", "Seward": "Western Kansas", "Sheridan": "Western Kansas",
        "Sherman": "Western Kansas", "Smith": "Western Kansas", "Stafford": "Western Kansas",
        "Stanton": "Western Kansas", "Stevens": "Western Kansas", "Thomas": "Western Kansas",
        "Trego": "Western Kansas", "Wallace": "Western Kansas", "Wichita": "Western Kansas",
    },
    "KY": {
        "Adair": "Kentucky", "Allen": "Kentucky", "Anderson": "Kentucky", "Ballard": "Kentucky",
        "Barren": "Kentucky", "Breckinridge": "Kentucky", "Bullitt": "Kentucky",
        "Butler": "Kentucky", "Caldwell": "Kentucky", "Calloway": "Kentucky",
        "Carlisle": "Kentucky", "Casey": "Kentucky", "Christian": "Kentucky",
        "Clinton": "Kentucky", "Crittenden": "Kentucky", "Cumberland": "Kentucky",
        "Daviess": "Kentucky", "Edmonson": "Kentucky", "Fulton": "Kentucky",
        "Graves": "Kentucky", "Grayson": "Kentucky", "Green": "Kentucky",
        "Hancock": "Kentucky", "Hardin": "Kentucky", "Hart": "Kentucky",
        "Henderson": "Kentucky", "Hickman": "Kentucky", "Hopkins": "Kentucky",
        "Jefferson": "Kentucky", "LaRue": "Kentucky", "Livingston": "Kentucky",
        "Logan": "Kentucky", "Lyon": "Kentucky", "Marion": "Kentucky",
        "Marshall": "Kentucky", "McCracken": "Kentucky", "McLean": "Kentucky",
        "Meade": "Kentucky", "Metcalfe": "Kentucky", "Monroe": "Kentucky",
        "Muhlenberg": "Kentucky", "Nelson": "Kentucky", "Ohio": "Kentucky",
        "Oldham": "Kentucky", "Russell": "Kentucky", "Simpson": "Kentucky",
        "Spencer": "Kentucky", "Taylor": "Kentucky", "Todd": "Kentucky",
        "Trigg": "Kentucky", "Union": "Kentucky", "Warren": "Kentucky",
        "Washington": "Kentucky", "Webster": "Kentucky",
        "Bath": "Lexington", "Bell": "Lexington", "Bourbon": "Lexington",
        "Boyd": "Lexington", "Boyle": "Lexington", "Bracken": "Lexington",
        "Breathitt": "Lexington", "Campbell": "Lexington", "Carroll": "Lexington",
        "Carter": "Lexington", "Clark": "Lexington", "Clay": "Lexington",
        "Elliott": "Lexington", "Estill": "Lexington", "Fayette": "Lexington",
        "Fleming": "Lexington", "Floyd": "Lexington", "Gallatin": "Lexington",
        "Garrard": "Lexington", "Grant": "Lexington", "Greenup": "Lexington",
        "Harlan": "Lexington", "Harrison": "Lexington", "Henry": "Lexington",
        "Jackson": "Lexington", "Jessamine": "Lexington", "Johnson": "Lexington",
        "Kenton": "Lexington", "Knott": "Lexington", "Knox": "Lexington",
        "Laurel": "Lexington", "Lawrence": "Lexington", "Lee": "Lexington",
        "Leslie": "Lexington", "Letcher": "Lexington", "Lewis": "Lexington",
        "Lincoln": "Lexington", "Madison": "Lexington", "Magoffin": "Lexington",
        "Martin": "Lexington", "Mason": "Lexington", "McCreary": "Lexington",
        "Menifee": "Lexington", "Mercer": "Lexington", "Montgomery": "Lexington",
        "Morgan": "Lexington", "Nicholas": "Lexington", "Owen": "Lexington",
        "Owsley": "Lexington", "Pendleton": "Lexington", "Perry": "Lexington",
        "Pike": "Lexington", "Powell": "Lexington", "Pulaski": "Lexington",
        "Robertson": "Lexington", "Rockcastle": "Lexington", "Rowan": "Lexington",
        "Scott": "Lexington", "Trimble": "Lexington", "Wayne": "Lexington",
        "Whitley": "Lexington", "Wolfe": "Lexington", "Woodford": "Lexington",
    },
    "MA": {
        "Barnstable": "Massachusetts", "Berkshire": "Western Massachusetts",
        "Bristol": "Massachusetts", "Dukes": "Massachusetts", "Essex": "Massachusetts",
        "Franklin": "Western Massachusetts", "Hampden": "Western Massachusetts",
        "Hampshire": "Western Massachusetts", "Middlesex": "Massachusetts",
        "Nantucket": "Massachusetts", "Norfolk": "Massachusetts", "Plymouth": "Massachusetts",
        "Suffolk": "Massachusetts", "Worcester": "Massachusetts",
    },
    "IN": {
        "Adams": "Northern Indiana", "Allen": "Northern Indiana",
        "Bartholomew": "Indianapolis", "Benton": "Northern Indiana",
        "Blackford": "Northern Indiana", "Brown": "Indianapolis",
        "Cass": "Northern Indiana", "Clark": "Indianapolis", "Clay": "Indianapolis",
        "Clinton": "Indianapolis", "Crawford": "Indianapolis", "Daviess": "Indianapolis",
        "Dearborn": "Indianapolis", "Decatur": "Indianapolis", "DeKalb": "Northern Indiana",
        "Delaware": "Northern Indiana", "Dubois": "Indianapolis", "Elkhart": "Northern Indiana",
        "Fayette": "Indianapolis", "Floyd": "Indianapolis", "Fountain": "Indianapolis",
        "Franklin": "Indianapolis", "Fulton": "Northern Indiana", "Gibson": "Indianapolis",
        "Grant": "Northern Indiana", "Greene": "Indianapolis", "Hamilton": "Indianapolis",
        "Hancock": "Indianapolis", "Harrison": "Indianapolis", "Hendricks": "Indianapolis",
        "Henry": "Indianapolis", "Howard": "Northern Indiana", "Huntington": "Northern Indiana",
        "Jackson": "Indianapolis", "Jasper": "Northern Indiana", "Jay": "Northern Indiana",
        "Jefferson": "Indianapolis", "Jennings": "Indianapolis", "Johnson": "Indianapolis",
        "Knox": "Indianapolis", "Kosciusko": "Northern Indiana", "LaGrange": "Northern Indiana",
        "Lake": "Northern Indiana", "LaPorte": "Northern Indiana", "Lawrence": "Indianapolis",
        "Madison": "Indianapolis", "Marion": "Indianapolis", "Marshall": "Northern Indiana",
        "Martin": "Indianapolis", "Miami": "Northern Indiana", "Monroe": "Indianapolis",
        "Montgomery": "Indianapolis", "Morgan": "Indianapolis", "Newton": "Northern Indiana",
        "Noble": "Northern Indiana", "Ohio": "Indianapolis", "Orange": "Indianapolis",
        "Owen": "Indianapolis", "Parke": "Indianapolis", "Perry": "Indianapolis",
        "Pike": "Indianapolis", "Porter": "Northern Indiana", "Posey": "Indianapolis",
        "Pulaski": "Northern Indiana", "Putnam": "Indianapolis", "Randolph": "Northern Indiana",
        "Ripley": "Indianapolis", "Rush": "Indianapolis", "Scott": "Indianapolis",
        "Shelby": "Indianapolis", "Spencer": "Indianapolis", "St Joseph": "Northern Indiana",
        "Starke": "Northern Indiana", "Steuben": "Northern Indiana", "Sullivan": "Indianapolis",
        "Switzerland": "Indianapolis", "Tippecanoe": "Indianapolis", "Tipton": "Indianapolis",
        "Union": "Indianapolis", "Vanderburgh": "Indianapolis", "Vermillion": "Indianapolis",
        "Vigo": "Indianapolis", "Wabash": "Northern Indiana", "Warren": "Indianapolis",
        "Warrick": "Indianapolis", "Washington": "Indianapolis", "Wayne": "Indianapolis",
        "Wells": "Northern Indiana", "White": "Northern Indiana", "Whitley": "Northern Indiana",
    },
    "MD": {
        "Allegany": "Maryland", "Anne Arundel": "Maryland", "Baltimore": "Maryland",
        "Calvert": "Maryland", "Carroll": "Maryland", "Cecil": "Maryland",
        "Charles": "Maryland", "Frederick": "Maryland", "Garrett": "Maryland",
        "Harford": "Maryland", "Howard": "Maryland", "Kent": "Maryland",
        "Queen Anne's": "Maryland", "St Mary's": "Maryland", "Talbot": "Maryland",
        "Washington": "Maryland", "Wicomico": "Maryland", "Worcester": "Maryland",
        "Montgomery": "Washington", "Prince George's": "Washington",
    },
    "NJ": {
        "Atlantic": "New Jersey", "Bergen": "Newark", "Burlington": "New Jersey",
        "Camden": "New Jersey", "Cape May": "New Jersey", "Cumberland": "New Jersey",
        "Essex": "Newark", "Gloucester": "New Jersey", "Hudson": "Newark",
        "Hunterdon": "New Jersey", "Mercer": "New Jersey", "Middlesex": "New Jersey",
        "Monmouth": "New Jersey", "Morris": "Newark", "Ocean": "New Jersey",
        "Passaic": "Newark", "Salem": "New Jersey", "Somerset": "New Jersey",
        "Sussex": "Newark", "Union": "Newark", "Warren": "Newark",
    },
}
