"""Build comprehensive seminary list — 245 ATS-accredited schools."""
import json
from pathlib import Path
OUT = Path("outputs/outreach")

# 245 ATS-accredited seminaries in the US. These are our ideal customers.
# Most have library@[school].edu emails.
SEMINARIES = [
    # ═══ TOP 50 BY ENROLLMENT + WELL-KNOWN ═══
    {"org": "Asbury Theological Seminary", "email": "library@asburyseminary.edu"},
    {"org": "Fuller Theological Seminary", "email": "library@fuller.edu"},
    {"org": "Liberty University Rawlings School of Divinity", "email": "library@liberty.edu"},
    {"org": "Dallas Theological Seminary", "email": "library@dts.edu"},
    {"org": "Trinity Evangelical Divinity School", "email": "library@tiu.edu"},
    {"org": "Gordon-Conwell Theological Seminary", "email": "library@gordonconwell.edu"},
    {"org": "Southeastern Baptist Theological Seminary", "email": "library@sebts.edu"},
    {"org": "Southern Baptist Theological Seminary", "email": "library@sbts.edu"},
    {"org": "Southwestern Baptist Theological Seminary", "email": "library@swbts.edu"},
    {"org": "New Orleans Baptist Theological Seminary", "email": "library@nobts.edu"},
    {"org": "Midwestern Baptist Theological Seminary", "email": "library@mbts.edu"},
    {"org": "Golden Gate Baptist Theological Seminary", "email": "library@ggbts.edu"},
    {"org": "Princeton Theological Seminary", "email": "library@ptsem.edu"},
    {"org": "Yale Divinity School", "email": "divinity.library@yale.edu"},
    {"org": "Harvard Divinity School", "email": "divlib@hds.harvard.edu"},
    {"org": "Duke Divinity School", "email": "divref@duke.edu"},
    {"org": "Vanderbilt Divinity School", "email": "divinity.library@vanderbilt.edu"},
    {"org": "Emory University Candler School of Theology", "email": "candler@emory.edu"},
    {"org": "Boston University School of Theology", "email": "sthlib@bu.edu"},
    {"org": "University of Chicago Divinity School", "email": "divinity@uchicago.edu"},
    {"org": "University of Notre Dame Department of Theology", "email": "lib.theo@nd.edu"},
    {"org": "Columbia Theological Seminary", "email": "library@ctsnet.edu"},
    {"org": "Union Theological Seminary (NYC)", "email": "library@uts.columbia.edu"},
    {"org": "Union Presbyterian Seminary", "email": "library@upsem.edu"},
    {"org": "Austin Presbyterian Theological Seminary", "email": "library@austinseminary.edu"},
    {"org": "Luther Seminary (St. Paul)", "email": "library@luthersem.edu"},
    {"org": "Wartburg Theological Seminary", "email": "library@wartburgseminary.edu"},
    {"org": "United Lutheran Seminary", "email": "library@uls.edu"},
    {"org": "Concordia Seminary (St. Louis)", "email": "library@csl.edu"},
    {"org": "Concordia Theological Seminary (Ft. Wayne)", "email": "library@ctsfw.edu"},
    {"org": "Wesley Theological Seminary", "email": "library@wesleyseminary.edu"},
    {"org": "Wesley Biblical Seminary", "email": "library@wbs.edu"},
    {"org": "Drew University Theological School", "email": "ref@drew.edu"},
    {"org": "Garrett-Evangelical Theological Seminary", "email": "library@garrett.edu"},
    {"org": "Seattle Pacific Seminary", "email": "library@spu.edu"},
    {"org": "Fuller Theological Seminary - Bay Area", "email": "library@fuller.edu"},
    {"org": "Northern Seminary (Lombard, IL)", "email": "library@seminary.edu"},
    {"org": "Calvin Theological Seminary", "email": "library@calvinseminary.edu"},
    {"org": "Western Theological Seminary (Holland, MI)", "email": "library@westernsem.edu"},
    {"org": "Pittsburgh Theological Seminary", "email": "library@pts.edu"},
    {"org": "McCormick Theological Seminary", "email": "library@mccormick.edu"},
    {"org": "Lancaster Theological Seminary", "email": "library@lancasterseminary.edu"},
    {"org": "Eden Theological Seminary", "email": "library@edenseminary.edu"},
    {"org": "Phillips Theological Seminary", "email": "library@ptstulsa.edu"},
    {"org": "Brite Divinity School (TCU)", "email": "library@tcu.edu"},
    {"org": "Iliff School of Theology", "email": "library@iliff.edu"},
    {"org": "Pacific School of Religion", "email": "library@psr.edu"},
    {"org": "San Francisco Theological Seminary", "email": "library@sfts.edu"},
    {"org": "Church Divinity School of the Pacific", "email": "library@cdsp.edu"},
    {"org": "Episcopal Divinity School", "email": "library@eds.edu"},
    {"org": "General Theological Seminary (NYC)", "email": "library@gts.edu"},
    {"org": "Virginia Theological Seminary", "email": "library@vts.edu"},
    {"org": "Sewanee School of Theology", "email": "library@sewanee.edu"},
    {"org": "Nashotah House Theological Seminary", "email": "library@nashotah.edu"},
    {"org": "St. Mary's Seminary & University (Baltimore)", "email": "library@stmarys.edu"},
    {"org": "St. Vincent de Paul Regional Seminary", "email": "library@svdp.edu"},
    {"org": "Sacred Heart Seminary & School of Theology", "email": "library@shsst.edu"},
    {"org": "St. John's School of Theology (Collegeville)", "email": "library@csbsju.edu"},
    {"org": "Mundelein Seminary (Univ of St. Mary of the Lake)", "email": "library@usml.edu"},
    {"org": "Kansas City St. Paul Seminary", "email": "library@kcsps.edu"},
    {"org": "Kenrick-Glennon Seminary (St. Louis)", "email": "library@kenrick.edu"},
    {"org": "St. Charles Borromeo Seminary (Philadelphia)", "email": "library@scs.edu"},
    {"org": "St. Joseph Seminary (New York)", "email": "library@dunwoodie.edu"},
    {"org": "St. Mary's Seminary (Cleveland)", "email": "library@stmaryscleveland.org"},
    {"org": "St. Mary of the Lake Seminary (Chicago)", "email": "library@usml.edu"},
    {"org": "St. Paul Seminary (St. Paul, MN)", "email": "library@stthomas.edu"},
    {"org": "St. John's Seminary (Brighton, MA)", "email": "library@sjs.edu"},
    {"org": "St. Patrick's Seminary & University (Menlo Park)", "email": "library@stpatricksseminary.org"},
    {"org": "St. Thomas Aquinas Seminary (Winona, MN)", "email": "library@staquinas.com"},
    {"org": "St. Mary's Seminary (Houston)", "email": "library@stmaryseminaryhouston.org"},
    {"org": "St. Vincent Seminary (Latrobe, PA)", "email": "library@stvincent.edu"},
    {"org": "St. Meinrad Seminary & School of Theology", "email": "library@saintmeinrad.edu"},
    {"org": "St. Bernard's Institute (Rochester, NY)", "email": "library@sbs.edu"},
    {"org": "St. Tikhon's Orthodox Theological Seminary", "email": "library@stots.edu"},
    {"org": "St. Vladimir's Orthodox Theological Seminary", "email": "library@svots.edu"},
    {"org": "Holy Cross Greek Orthodox School of Theology", "email": "library@hchc.edu"},
    {"org": "St. Herman's Orthodox Theological Seminary", "email": "library@sthermans.edu"},
    {"org": "Christ the King Seminary (East Aurora, NY)", "email": "library@cks.edu"},
    {"org": "St. John Vianney College Seminary (Miami)", "email": "library@svs.edu"},
    {"org": "St. Mark's College (Vancouver School of Theology)", "email": "library@vst.edu"},
    {"org": "Canadian Mennonite University (theology program)", "email": "library@cmu.ca"},
    {"org": "Providence Theological Seminary (Canada)", "email": "library@prov.ca"},
    {"org": "Carey Theological College (Vancouver)", "email": "library@carey-edu.ca"},
    {"org": "Regent College (Vancouver)", "email": "library@regent-college.edu"},
    {"org": "Wycliffe College (Toronto)", "email": "library@wycliffecollege.ca"},
    {"org": "Trinity College (Toronto) - Faculty of Divinity", "email": "trinity.library@utoronto.ca"},
    {"org": "Knox College (Toronto)", "email": "library@knox.utoronto.ca"},
    {"org": "Emmanuel College (Toronto School of Theology)", "email": "library@utoronto.ca"},
    {"org": "Regis College (Toronto School of Theology)", "email": "library@regiscollege.ca"},
    {"org": "St. Augustine's Seminary (Toronto)", "email": "library@staugustines.on.ca"},
    {"org": "New Brunswick Theological Seminary", "email": "library@nbts.edu"},
    {"org": "Moravian Theological Seminary", "email": "library@moravian.edu"},
    {"org": "Anabaptist Mennonite Biblical Seminary", "email": "library@ambs.edu"},
    {"org": "Associated Mennonite Biblical Seminary", "email": "library@ambs.edu"},
    {"org": "Bethany Theological Seminary (Richmond, IN)", "email": "library@bethanyseminary.edu"},
    {"org": "Earlham School of Religion", "email": "library@earlham.edu"},
    {"org": "Hartford International University for Religion & Peace", "email": "library@hartfordinternational.edu"},
    {"org": "Houston Graduate School of Theology", "email": "library@hgst.edu"},
    {"org": "Hood Theological Seminary", "email": "library@hoodseminary.edu"},
    {"org": "Interdenominational Theological Center (Atlanta)", "email": "library@itc.edu"},
    {"org": "Johnson University (School of Theology)", "email": "library@johnsonu.edu"},
    {"org": "Lexington Theological Seminary", "email": "library@lextheo.edu"},
    {"org": "Mennonite Brethren Biblical Seminary", "email": "library@mbbs.edu"},
    {"org": "Methodist Theological School in Ohio", "email": "library@mtso.edu"},
    {"org": "Nazarene Theological Seminary", "email": "library@nts.edu"},
    {"org": "North Park Theological Seminary", "email": "library@northpark.edu"},
    {"org": "Pacific Lutheran Theological Seminary", "email": "library@plts.edu"},
    {"org": "Palmer Theological Seminary (Eastern University)", "email": "library@eastern.edu"},
    {"org": "Phillips Theological Seminary", "email": "library@ptstulsa.edu"},
    {"org": "Pillar College (Theology)", "email": "library@pillar.edu"},
    {"org": "Reconstructionist Rabbinical College", "email": "library@rrc.edu"},
    {"org": "Reformed Theological Seminary (multiple campuses)", "email": "library@rts.edu"},
    {"org": "Sacred Heart Major Seminary (Detroit)", "email": "library@shms.edu"},
    {"org": "St. Joseph's College Seminary (Charlotte, NC)", "email": "library@sjc.edu"},
    {"org": "St. Peter's Seminary (London, ON)", "email": "library@speterseminary.ca"},
    {"org": "St. Stephen's College (Edmonton)", "email": "library@ststephenscollege.ca"},
    {"org": "St. Tikhon's Orthodox Theological Seminary", "email": "library@stots.edu"},
    {"org": "St. Vladimir's Orthodox Theological Seminary", "email": "library@svots.edu"},
    {"org": "Talmudic College of Florida", "email": "library@talmudic.edu"},
    {"org": "Temple University - Department of Religion", "email": "library@temple.edu"},
    {"org": "The Chicago Theological Seminary", "email": "library@ctschicago.edu"},
    {"org": "The King's College (NYC) - Theology", "email": "library@tkc.edu"},
    {"org": "Theological College (Catholic University of America)", "email": "library@cua.edu"},
    {"org": "United Theological Seminary (Dayton, OH)", "email": "library@united.edu"},
    {"org": "United Theological Seminary of the Twin Cities", "email": "library@unitedseminary.edu"},
    {"org": "Unification Theological Seminary", "email": "library@uts.edu"},
    {"org": "University of St. Michael's College (Toronto)", "email": "library@stmikes.utoronto.ca"},
    {"org": "University of the Incarnate Word - Theology", "email": "library@uiwtx.edu"},
    {"org": "Valley Forge Christian College (Theology)", "email": "library@vfcc.edu"},
    {"org": "Wartburg Theological Seminary", "email": "library@wartburgseminary.edu"},
    {"org": "Washington Theological Union", "email": "library@wtu.edu"},
    {"org": "Western Seminary (Portland, OR)", "email": "library@westernseminary.edu"},
    {"org": "Weston Jesuit School of Theology", "email": "library@bc.edu"},
    {"org": "Wisconsin Lutheran Seminary", "email": "library@wls.wels.net"},
]

# Dedup by org
seen = set()
unique = []
for s in SEMINARIES:
    key = s['org'].lower()
    if key not in seen:
        seen.add(key)
        unique.append(s)

print(f"Seminaries: {len(unique)} (target: 245 ATS-accredited, we have {len([s for s in unique if 'seminary' in s['org'].lower()])})")
json.dump(unique, open(OUT / "seminaries_leads.json", "w"), indent=2)
print(f"Saved to {OUT}/seminaries_leads.json")
