"""
TORONTO JEWISH OUTREACH — UJA Federation, CIJA, Security Network, and U of T contacts.
GRID has the most complete dataset on Jewish infrastructure worldwide.
Includes Jewish world maps generated by gen_jewish_maps.py.
"""
import json, smtplib, time, os, sys
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

PWD = os.environ.get("GMAIL_APP_PASSWORD")
if not PWD:
    import subprocess
    r = subprocess.run(["powershell", "-c", "[Environment]::GetEnvironmentVariable('GMAIL_APP_PASSWORD','User')"], capture_output=True, text=True)
    PWD = r.stdout.strip()
if not PWD:
    print("Set GMAIL_APP_PASSWORD"); sys.exit(1)

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
FROM = "Charles Prescott <charlesaprescottjr@gmail.com>"
REPLY_TO = "charlesaprescott@outlook.com"
INTERVAL = 180  # 3 minutes
OUT = Path("outputs/outreach")
OUT.mkdir(parents=True, exist_ok=True)

SIG = """Charles Prescott
Creator, GRID — Global Religious Infrastructure Database
JD, LLM (Taxation) | Trinity College, University of Toronto (incoming Fall 2026)
charlesaprescottjr@gmail.com | 843-504-4542"""

# ═══════════════════════════════════════════════════════════════
# TORONTO JEWISH CONTACTS
# ═══════════════════════════════════════════════════════════════

CONTACTS = [
    # ═══ TIER 1: UJA & CIJA (merged UJA into single email to avoid triplicate) ═══
    {
        "org": "UJA Federation of Greater Toronto",
        "contact": "Adam Minsky (President & CEO) / Ken Tanenbaum (Board Chair) / Community Security Director",
        "email": None,
        "phone": "416-635-2883",
        "sector": "Federation / Security / Planning",
        "tier": 1,
        "notes": "Covers all three UJA contacts in one email. Strategic buyer; oversees global allocations. Also ask for Director of Community Security and Planning & Israel Engagement.",
        "send_via": "info@jewishtoronto.com",
        "subject_override": "GRID: Jewish Infrastructure Dataset — For UJA Leadership (Planning, Security & Allocations)",
    },
    {
        "org": "CIJA — Centre for Israel and Jewish Affairs",
        "contact": "Catherine Morrow — Associate Director, Development",
        "email": "cmorrow@cija.ca",
        "phone": "(416) 925-7499 x224",
        "sector": "Advocacy / Policy",
        "tier": 1,
        "notes": "BEST CIJA entry point. Development officers understand data assets.",
        "send_via": "cmorrow@cija.ca",
    },
    {
        "org": "URJ — Union for Reform Judaism (North America)",
        "contact": "URJ Member Support / Data & Research Team",
        "email": "URJ1800@URJ.org",
        "phone": None,
        "sector": "Umbrella / Denomination",
        "tier": 1,
        "notes": "Largest Jewish denomination in North America (~1,800 congregations). GRID has 1,810 Reform entries mapped globally. Perfect data licensing / congregational mapping buyer.",
        "send_via": "URJ1800@URJ.org",
        "subject_override": "GRID: 1,810 Reform Synagogues Mapped Worldwide — Dataset for URJ Congregational Planning",
    },
    {
        "org": "Secure Community Network (SCN) — National Jewish Security",
        "contact": "SCN — NSGP / Security Support Team",
        "email": "nsgpsupport@securecommunitynetwork.org",
        "phone": None,
        "sector": "Security",
        "tier": 1,
        "notes": "SCN is the official safety & security organization of the Jewish community in North America. NSGP = Nonprofit Security Grant Program. GRID maps every Jewish institution — direct security planning application.",
        "send_via": "nsgpsupport@securecommunitynetwork.org",
        "subject_override": "GRID: Complete Jewish Infrastructure Map — Every Synagogue GPS-Located for SCN Security Planning",
    },

    # ═══ TIER 1: US JEWISH FOUNDATIONS ═══
    {
        "org": "Jim Joseph Foundation — Jewish Education",
        "contact": "Dawne Bear Novicoff — Acting President & CEO / COO",
        "email": "info@jimjosephfoundation.org",
        "phone": "(415) 658-8730",
        "sector": "Foundation",
        "tier": 1,
        "notes": "$4M+ grants to Birthright, Hillel, Jewish Camp. Jewish education & engagement focus. GRID maps every Jewish educational site — direct alignment with their mission to reach unengaged young Jews.",
        "send_via": "info@jimjosephfoundation.org",
        "subject_override": "GRID: Mapping Jewish Education Infrastructure — Dataset for Jim Joseph Foundation Grantees",
    },
    {
        "org": "Schusterman Family Philanthropies",
        "contact": "Lisa Eisen — VP / Jewish Community Team",
        "email": "information@schusterman.org",
        "phone": None,
        "sector": "Foundation",
        "tier": 1,
        "notes": "One of the largest Jewish philanthropies. Funds Jewish identity, Israel engagement, and community connectivity. GRID data directly supports their strategic grantmaking with spatial intelligence.",
        "send_via": "information@schusterman.org",
        "subject_override": "GRID: Jewish Diaspora Infrastructure Map — Data for Schusterman's Jewish Community Strategy",
    },
    {
        "org": "Ruderman Family Foundation",
        "contact": "Foundation Leadership — Israel-Diaspora Relations",
        "email": "support@rudermanfoundation.org",
        "phone": None,
        "sector": "Foundation",
        "tier": 1,
        "notes": "Focus: Israel-American Jewish relations + disability inclusion. GRID maps the physical infrastructure of the diaspora — directly relevant to Israel-diaspora relationship work.",
        "send_via": "support@rudermanfoundation.org",
        "subject_override": "GRID: Mapping Israel-Diaspora Jewish Infrastructure — Dataset for Ruderman Foundation",
    },
    {
        "org": "Crown Family Philanthropies — Chicago",
        "contact": "Evan Hochberg — President / Jewish Community & Israel Lead Pursuit",
        "email": "grants@crownfamilyphilanthropies.org",
        "phone": "(312) 750-6671",
        "sector": "Foundation",
        "tier": 1,
        "notes": "$46M/yr grantmaking, $435M assets. Jewish Community & Israel is a named Lead Pursuit. Chicago-based but funds nationally. Invitation-only — but this is an inbound data partnership pitch, not a grant ask.",
        "send_via": "grants@crownfamilyphilanthropies.org",
        "subject_override": "GRID: Jewish Infrastructure Mapping — Data Partnership for Crown Family Philanthropies",
    },
    {
        "org": "Jewish Funders Network (JFN)",
        "contact": "Maya Foner — Network / Matching Grants",
        "email": "mfoner@jfunders.org",
        "phone": None,
        "sector": "Foundation Network",
        "tier": 1,
        "notes": "NETWORK MULTIPLIER. JFN connects Jewish funders worldwide. If they share GRID with their membership, it reaches dozens of foundations at once. Maya Foner handles peer networks.",
        "send_via": "mfoner@jfunders.org",
        "subject_override": "GRID: Jewish Infrastructure Dataset — For JFN Member Foundations",
    },
    {
        "org": "The Harry and Jeanette Weinberg Foundation",
        "contact": "Foundation Leadership — Grants & Strategy",
        "email": "info@hjweinbergfoundation.org",
        "phone": "(410) 654-8500",
        "sector": "Foundation",
        "tier": 2,
        "notes": "One of the largest US foundations ($2.8B assets). Funds in Baltimore, Hawaii, Israel, NYC, NE PA, San Francisco. Doesn't fund religious institutions directly but data/research is not a religious grant.",
        "send_via": "info@hjweinbergfoundation.org",
        "subject_override": "GRID: Jewish Community Infrastructure Data — For Weinberg Foundation Planning",
    },
    {
        "org": "Maimonides Fund",
        "contact": "Foundation Leadership",
        "email": "info@maimonidesfund.org",
        "phone": None,
        "sector": "Foundation",
        "tier": 2,
        "notes": "Jewish education & identity focus. Funds innovative Jewish initiatives. Mapping data supports strategic investment decisions.",
        "send_via": "info@maimonidesfund.org",
    },
    {
        "org": "The Wexner Foundation",
        "contact": "Foundation Leadership — Jewish Leadership Programs",
        "email": "info@wexnerfoundation.org",
        "phone": None,
        "sector": "Foundation",
        "tier": 2,
        "notes": "Trains Jewish professional & volunteer leaders. Wexner Fellows are the people who run federations, synagogues, and Jewish orgs. They're the end users of this data.",
        "send_via": "info@wexnerfoundation.org",
        "subject_override": "GRID: Jewish Infrastructure Data — For Wexner Fellows & Jewish Communal Leaders",
    },
    {
        "org": "The Gottesman Fund",
        "contact": "Foundation Leadership",
        "email": "info@gottesmanfund.org",
        "phone": None,
        "sector": "Foundation",
        "tier": 2,
        "notes": "Jewish philanthropy with interests in education, Israel, and community. Mapping data supports strategic giving decisions.",
        "send_via": "info@gottesmanfund.org",
    },

    # ═══ TIER 1: JEWISH RESEARCH & DATA ORGANIZATIONS ═══
    {
        "org": "Berman Jewish DataBank (at JFNA)",
        "contact": "Laurence Kotler-Berkowitz — Senior Director, Research & Analysis / Berman DataBank",
        "email": "Laurence.Kotler-Berkowitz@jewishfederations.org",
        "phone": "(212) 284-6500",
        "sector": "Research / Data",
        "tier": 1,
        "notes": "THE central repository for Jewish demographic data. Commissions national & local community studies. GRID is the institutional-infrastructure complement to their survey data — the perfect data partnership.",
        "send_via": "Laurence.Kotler-Berkowitz@jewishfederations.org",
        "subject_override": "GRID: 27K Jewish Institutions Mapped Worldwide — Complementary Dataset for Berman DataBank",
    },
    {
        "org": "Cohen Center for Modern Jewish Studies / Steinhardt Social Research Institute (Brandeis)",
        "contact": "Leonard Saxe — Director, Cohen Center / Steinhardt Institute",
        "email": "saxe@brandeis.edu",
        "phone": "(781) 736-2129",
        "sector": "Research / Data",
        "tier": 1,
        "notes": "Largest academic Jewish demography shop in the US. Produces national Jewish population estimates. GRID is ground-truth institutional data that complements their survey-based population research.",
        "send_via": "saxe@brandeis.edu",
        "subject_override": "GRID: Jewish Institutional Infrastructure Dataset — Ground-Truth Data for Brandeis Demography Research",
    },
    {
        "org": "Jewish Federations of North America (JFNA)",
        "contact": "Eric Fingerhut — President & CEO / Alisa Bodner — VP Marketing & Communications",
        "email": "info@jewishfederations.org",
        "phone": "(212) 284-6500",
        "sector": "Umbrella / Federation",
        "tier": 1,
        "notes": "Umbrella for 146 local Jewish federations. Each does community studies. GRID gives them a national GIS layer of every Jewish institution — synagogues, JCCs, schools, camps — cross-walkable to Census/ACS demographics.",
        "send_via": "info@jewishfederations.org",
        "subject_override": "GRID: Complete Jewish Institutional Map — 16,895 US Sites for JFNA Federation Planning",
    },
    {
        "org": "Pew Research Center — Religion & Public Life",
        "contact": "Alan Cooperman — Director of Religion Research / Greg Smith — Associate Director",
        "email": "info@pewresearch.org",
        "phone": "(202) 419-4372",
        "sector": "Research / Data",
        "tier": 1,
        "notes": "Did 'Jewish Americans in 2020.' GRID provides the institutional geography layer to complement Pew's survey data. Could enable spatial analysis of survey respondents against synagogue proximity.",
        "send_via": "info@pewresearch.org",
        "subject_override": "GRID: Jewish Institutional Geography Dataset — Spatial Complement to Pew's Jewish Americans Survey",
    },
    {
        "org": "American Jewish Committee (AJC)",
        "contact": "Meggie Wyschogrod Fredman — Senior Director, Alexander Young Leadership Dept / Research Team",
        "email": "contact@ajc.org",
        "phone": "(212) 751-4000",
        "sector": "Advocacy / Policy",
        "tier": 1,
        "notes": "Global Jewish advocacy with a research arm. Published antisemitism surveys. GRID maps institutional presence for security/advocacy planning. Request routing to State of Antisemitism research team.",
        "send_via": "contact@ajc.org",
        "subject_override": "GRID: Global Jewish Infrastructure Map — For AJC Research & Advocacy",
    },
    {
        "org": "Jewish People Policy Institute (JPPI) — Jerusalem",
        "contact": "Shmuel Rosner — Senior Fellow / Research Team",
        "email": "info@jppi.org.il",
        "phone": None,
        "sector": "Research / Data",
        "tier": 1,
        "notes": "Jerusalem-based think tank doing global Jewish policy research. Would value the full worldwide dataset (172 countries), not just US. Israel-based funder perspective — different budget cycle.",
        "send_via": "info@jppi.org.il",
        "subject_override": "GRID: Global Jewish Diaspora Infrastructure — 172-Country Dataset for JPPI Research",
    },

    # ═══ TIER 2: MORE FOUNDATIONS ═══
    {
        "org": "Mandel Foundation — Jack, Joseph and Morton Mandel",
        "contact": "Jehuda Reinharz — President & CEO / Jewish Leadership Programs",
        "email": "info@mandelfoundation.org",
        "phone": "(216) 231-3900",
        "sector": "Foundation",
        "tier": 2,
        "notes": "Major funder of Jewish leadership & community planning research. Also funds Brandeis (Mandel Center for Studies in Jewish Education). Natural fit for data-driven community planning.",
        "send_via": "info@mandelfoundation.org",
        "subject_override": "GRID: Jewish Community Infrastructure Data — For Mandel Foundation Leadership Programs",
    },
    {
        "org": "The Russell Berrie Foundation",
        "contact": "Foundation Leadership — Jewish Life & Interfaith Bridge-Building",
        "email": "info@russellberriefoundation.org",
        "phone": "(201) 728-0700",
        "sector": "Foundation",
        "tier": 2,
        "notes": "NJ-based, funds Jewish continuity, interfaith bridge-building, and Israel engagement. Data supports geographic targeting of community investments.",
        "send_via": "info@russellberriefoundation.org",
        "subject_override": "GRID: Jewish Infrastructure Mapping — For Russell Berrie Foundation Grantees",
    },
    {
        "org": "Koret Foundation — SF Bay Area",
        "contact": "Foundation Leadership — Jewish Community",
        "email": "info@koretfoundation.org",
        "phone": "(415) 882-7740",
        "sector": "Foundation",
        "tier": 2,
        "notes": "SF-based, funds Jewish peoplehood, Israel studies, and Bay Area Jewish life. Bay Area has 198+ Jewish institutions in GRID. Data supports regional community planning.",
        "send_via": "info@koretfoundation.org",
        "subject_override": "GRID: Jewish Infrastructure Data — Bay Area & Global — For Koret Foundation",
    },
    {
        "org": "The Marcus Foundation — Atlanta",
        "contact": "Foundation Leadership — Jewish & Israel Programs",
        "email": "info@marcusfoundation.org",
        "phone": "(404) 949-3320",
        "sector": "Foundation",
        "tier": 2,
        "notes": "Bernie Marcus (Home Depot co-founder). Funds Jewish causes, Israel, and medical research. Large foundation with Jewish community focus.",
        "send_via": "info@marcusfoundation.org",
        "subject_override": "GRID: Jewish Infrastructure Data — For Marcus Foundation Community Investments",
    },

    # ═══ TIER 2: MAJOR LOCAL FEDERATIONS (separate from JFNA umbrella) ═══
    {
        "org": "UJA-Federation of New York",
        "contact": "Eric S. Goldstein — CEO / Research & Planning Dept",
        "email": "info@ujafedny.org",
        "phone": "(212) 980-1000",
        "sector": "Federation",
        "tier": 2,
        "notes": "Largest local Jewish federation. NY has 6,488 Jewish institutions in GRID — the densest coverage anywhere. They just completed a $100M+ community study. They spend real money on data.",
        "send_via": "info@ujafedny.org",
        "subject_override": "GRID: 6,488 New York Jewish Institutions Mapped — Dataset for UJA-NY Community Planning",
    },
    {
        "org": "Combined Jewish Philanthropies of Greater Boston",
        "contact": "Marc Baker — President & CEO / Planning & Strategy Team",
        "email": "welcome@cjp.org",
        "phone": "(617) 457-8500",
        "sector": "Federation",
        "tier": 2,
        "notes": "Boston's Jewish federation. Brandeis is in their backyard — natural research partner. Boston has 477+ Jewish institutions mapped. Data supports their community planning & allocations.",
        "send_via": "welcome@cjp.org",
        "subject_override": "GRID: Boston Jewish Infrastructure Map — Dataset for CJP Community Planning",
    },
    {
        "org": "Jewish United Fund of Metropolitan Chicago",
        "contact": "Lonnie Nasatir — President / Planning & Allocations Team",
        "email": "info@juf.org",
        "phone": "(312) 357-4800",
        "sector": "Federation",
        "tier": 2,
        "notes": "Chicago's Jewish federation. Chicago has 452+ Jewish institutions mapped. Crown Family Philanthropies is local — possible warm intro if Crown contact converts.",
        "send_via": "info@juf.org",
        "subject_override": "GRID: Chicago Jewish Infrastructure Map — Dataset for JUF Community Planning",
    },
    {
        "org": "Jewish Federation of Greater Los Angeles",
        "contact": "Rabbi Noah Farkas — President & CEO / Planning & Strategy",
        "email": "info@jewishla.org",
        "phone": "(323) 761-8000",
        "sector": "Federation",
        "tier": 2,
        "notes": "LA's Jewish federation. LA metro has 996+ Jewish institutions mapped (second only to NY). Data supports community planning across a vast geographic area.",
        "send_via": "info@jewishla.org",
        "subject_override": "GRID: LA Jewish Infrastructure Map — Dataset for JFEDLA Community Planning",
    },

    # ═══ TIER 3: ADDITIONAL ACADEMIC & RESEARCH ═══
    {
        "org": "Association for Jewish Studies (AJS)",
        "contact": "Warren Hoffman — Executive Director",
        "email": "ajs@associationforjewishstudies.org",
        "phone": "(917) 606-8249",
        "sector": "Academic",
        "tier": 3,
        "notes": "NETWORK MULTIPLIER. Largest learned society for Jewish studies. Their membership (professors, researchers) would be direct users of the data. They can share with their listserv/conference.",
        "send_via": "ajs@associationforjewishstudies.org",
        "subject_override": "GRID: Jewish Infrastructure Dataset — For AJS Research Community",
    },
    {
        "org": "Steinhardt Institute for the Study of Religion (NYU)",
        "contact": "Director / Research Team",
        "email": "steinhardt.institute@nyu.edu",
        "phone": None,
        "sector": "Academic",
        "tier": 3,
        "notes": "Studies American Judaism & religion quantitatively. NYU is in the heart of NY Jewish community (6,488 institutions). Natural academic buyer.",
        "send_via": "steinhardt.institute@nyu.edu",
        "subject_override": "GRID: Jewish Infrastructure Spatial Dataset — For NYU Steinhardt Institute Research",
    },
    {
        "org": "Center for Jewish History — NYC",
        "contact": "Research & Collections Team",
        "email": "inquiries@cjh.org",
        "phone": "(212) 294-8301",
        "sector": "Academic / Archive",
        "tier": 3,
        "notes": "Houses YIVO, American Jewish Historical Society, Leo Baeck Institute. Could use GRID for historical GIS — mapping pre-war vs post-war Jewish institutional geography.",
        "send_via": "inquiries@cjh.org",
        "subject_override": "GRID: Jewish Institutional Geography — Historical GIS Dataset for Center for Jewish History",
    },

    # ═══ TIER 1: KEY JEWISH DEMOGRAPHY SCHOLARS ═══
    {
        "org": "Sergio DellaPergola — Hebrew University (THE Jewish Demographer)",
        "contact": "Prof. Sergio DellaPergola — Professor Emeritus, Avraham Harman Institute of Contemporary Jewry",
        "email": "sergioa@huji.ac.il",
        "phone": None,
        "sector": "Academic",
        "tier": 1,
        "notes": "THE world's leading Jewish demographer. Authors the annual World Jewish Population chapter in the American Jewish Year Book since 1982. Advised Pew's Jewish Americans surveys. Advised Israel's President, Jewish Agency, CBS. GRID is the institutional-infrastructure dataset he's never had — he works with survey data. This would transform his research.",
        "send_via": "sergioa@huji.ac.il",
        "subject_override": "GRID: 27K-Site Global Jewish Infrastructure Map — For Your World Jewish Population Research",
    },
    {
        "org": "Ira Sheskin — University of Miami (Jewish Community Geographer)",
        "contact": "Prof. Ira M. Sheskin — Chair, Geography & Sustainable Development; Director, Jewish Demography Project",
        "email": "isheskin@miami.edu",
        "phone": "(305) 284-6693",
        "sector": "Academic",
        "tier": 1,
        "notes": "Geography professor who has conducted 45+ local Jewish community studies. Co-editor of the American Jewish Year Book. He's BOTH a geographer and a Jewish demographer — GRID is literally exactly what he does. This is the single most aligned academic on the planet.",
        "send_via": "isheskin@miami.edu",
        "subject_override": "GRID: Every Synagogue GPS-Mapped — A Geographer's Dataset for Jewish Community Studies",
    },
    {
        "org": "Arnold Dashefsky — UConn (American Jewish Year Book Editor)",
        "contact": "Prof. Arnold Dashefsky — Professor Emeritus of Sociology; Director, Center for Judaic Studies",
        "email": "arnold.dashefsky@uconn.edu",
        "phone": "(860) 509-9542",
        "sector": "Academic",
        "tier": 1,
        "notes": "Co-editor of the American Jewish Year Book (with Sheskin). The AJYB publishes annual Jewish population estimates — GRID is the institutional layer they've never been able to include. Also directs UConn's Center for Judaic Studies.",
        "send_via": "arnold.dashefsky@uconn.edu",
        "subject_override": "GRID: Jewish Institutional Infrastructure Dataset — For the American Jewish Year Book",
    },

    # ═══ TIER 1: ISRAELI DIASPORA RESEARCH CENTERS ═══
    {
        "org": "Goldstein-Goren Diaspora Research Center — Tel Aviv University",
        "contact": "Director / Research Team — Goldstein-Goren Diaspora Research Center",
        "email": "diaspora@tauex.tau.ac.il",
        "phone": "+972-3-6409799",
        "sector": "Academic",
        "tier": 1,
        "notes": "Israel's premier academic center for diaspora studies. Houses the Mehlman Library (one of the world's largest collections on Jewish diaspora). GRID maps the physical infrastructure of the diaspora they study — synagogues, schools, community centers in 172 countries.",
        "send_via": "diaspora@tauex.tau.ac.il",
        "subject_override": "GRID: Global Jewish Diaspora Infrastructure — 172-Country Dataset for TAU Diaspora Research",
    },
    {
        "org": "Avraham Harman Institute of Contemporary Jewry — Hebrew University",
        "contact": "Director / Research Team — Institute of Contemporary Jewry",
        "email": "ICJ@savion.huji.ac.il",
        "phone": "+972-2-588-1703",
        "sector": "Academic",
        "tier": 1,
        "notes": "Hebrew University's flagship Jewish research institute. DellaPergola's home institution. Publishes Studies in Contemporary Jewry. Houses the Division of Jewish Demography and Statistics. GRID is directly relevant to every research division.",
        "send_via": "ICJ@savion.huji.ac.il",
        "subject_override": "GRID: Global Jewish Infrastructure Dataset — For Hebrew University Contemporary Jewry Research",
    },

    # ═══ TIER 2: MAJOR JEWISH STUDIES CENTERS (US Universities) ═══
    {
        "org": "Frankel Center for Judaic Studies — University of Michigan",
        "contact": "Director / Research Team",
        "email": "judaicstudies@umich.edu",
        "phone": "(734) 763-9047",
        "sector": "Academic",
        "tier": 2,
        "notes": "One of the largest Jewish Studies centers in the US. Faculty include experts in American Jewish history, diaspora, and demography. Would use GRID for research and teaching.",
        "send_via": "judaicstudies@umich.edu",
        "subject_override": "GRID: Jewish Infrastructure Spatial Dataset — For Michigan Judaic Studies Research",
    },
    {
        "org": "Center for Jewish Studies — Harvard University",
        "contact": "Director / Research Team",
        "email": "cjs@fas.harvard.edu",
        "phone": "(617) 495-4326",
        "sector": "Academic",
        "tier": 2,
        "notes": "Harvard's Center for Jewish Studies. Faculty include experts in Jewish history, diaspora, and culture. Prestigious affiliation adds credibility — if Harvard uses GRID, others follow.",
        "send_via": "cjs@fas.harvard.edu",
        "subject_override": "GRID: Global Jewish Infrastructure Dataset — For Harvard Jewish Studies Research",
    },
    {
        "org": "Katz Center for Advanced Judaic Studies — University of Pennsylvania",
        "contact": "Director / Research Team",
        "email": "katz-center@sas.upenn.edu",
        "phone": "(215) 238-1290",
        "sector": "Academic",
        "tier": 2,
        "notes": "Penn's advanced Jewish studies institute. Hosts fellows each year on themed research topics. GRID could support a fellowship year on Jewish geography/diaspora mapping.",
        "send_via": "katz-center@sas.upenn.edu",
        "subject_override": "GRID: Jewish Infrastructure Dataset — For Penn Katz Center Fellowship Research",
    },
    {
        "org": "Taub Center for Israel Studies — NYU",
        "contact": "Director / Research Team",
        "email": "taub.center@nyu.edu",
        "phone": "(212) 998-8981",
        "sector": "Academic",
        "tier": 2,
        "notes": "NYU's Israel Studies center. Focus on modern Israel and its relationship with the diaspora. GRID maps the physical infrastructure of diaspora-Israel connections — synagogues, federations, Chabad houses.",
        "send_via": "taub.center@nyu.edu",
        "subject_override": "GRID: Jewish Diaspora Infrastructure Map — For NYU Taub Center Israel-Diaspora Research",
    },
    {
        "org": "Taube Center for Jewish Studies — Stanford University",
        "contact": "Director / Research Team",
        "email": "jewishstudies@stanford.edu",
        "phone": "(650) 723-1591",
        "sector": "Academic",
        "tier": 2,
        "notes": "Stanford's Jewish Studies program. Strong digital humanities focus — could integrate GRID into spatial humanities/digital mapping projects.",
        "send_via": "jewishstudies@stanford.edu",
        "subject_override": "GRID: Jewish Infrastructure Geospatial Data — For Stanford Jewish Studies Digital Humanities",
    },
    {
        "org": "Alan D. Leve Center for Jewish Studies — UCLA",
        "contact": "Director / Research Team",
        "email": "cjs@humnet.ucla.edu",
        "phone": "(310) 825-5387",
        "sector": "Academic",
        "tier": 2,
        "notes": "UCLA's Jewish Studies center. LA has the second-largest US Jewish community (996+ institutions). Strong local research angle + global scope.",
        "send_via": "cjs@humnet.ucla.edu",
        "subject_override": "GRID: Jewish Infrastructure Dataset — LA to Global — For UCLA Jewish Studies",
    },
    {
        "org": "Schusterman Center for Jewish Studies — UT Austin",
        "contact": "Director / Research Team",
        "email": "jewishstudies@austin.utexas.edu",
        "phone": "(512) 471-1914",
        "sector": "Academic",
        "tier": 3,
        "notes": "UT Austin's Jewish Studies program. Schusterman-funded (same family as the foundation in Tier 1). Texas has 278+ Jewish institutions — growing Sunbelt community.",
        "send_via": "jewishstudies@austin.utexas.edu",
        "subject_override": "GRID: Jewish Infrastructure Dataset — For UT Austin Jewish Studies Research",
    },
    {
        "org": "Borns Jewish Studies Program — Indiana University",
        "contact": "Director / Research Team",
        "email": "jsp@indiana.edu",
        "phone": "(812) 855-0453",
        "sector": "Academic",
        "tier": 3,
        "notes": "One of the oldest Jewish Studies programs in the US (founded 1972). Strong in Jewish history, diaspora, and cultural studies.",
        "send_via": "jsp@indiana.edu",
        "subject_override": "GRID: Jewish Infrastructure Spatial Data — For IU Borns Jewish Studies",
    },
    {
        "org": "Mosse/Weinstein Center for Jewish Studies — UW Madison",
        "contact": "Director / Research Team",
        "email": "jewishstudies@cjs.wisc.edu",
        "phone": "(608) 263-2205",
        "sector": "Academic",
        "tier": 3,
        "notes": "UW Madison's Jewish Studies center. Strong sociology of Judaism program. Could integrate GRID into demography and spatial analysis research.",
        "send_via": "jewishstudies@cjs.wisc.edu",
        "subject_override": "GRID: Jewish Infrastructure Dataset — For UW Madison Jewish Studies Research",
    },

    # ═══ TIER 2: JEWISH ACADEMIC JOURNALS & PUBLICATIONS ═══
    {
        "org": "American Jewish Year Book (Editors: Dashefsky, Sheskin, DellaPergola)",
        "contact": "Editorial Team — American Jewish Year Book / Berman DataBank",
        "email": "Laurence.Kotler-Berkowitz@jewishfederations.org",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "The AJYB publishes annual Jewish population estimates and institutional directories. GRID is the GIS layer they've never had. Already pitching the editors individually (DellaPergola, Sheskin, Dashefsky) — this is a follow-up to the publication itself.",
        "send_via": "Laurence.Kotler-Berkowitz@jewishfederations.org",
        "subject_override": "GRID: Jewish Institutional GIS Data — A New Section for the American Jewish Year Book?",
    },
    {
        "org": "Contemporary Jewry Journal (ASSJ / Springer)",
        "contact": "Harriet Hartman — Editor-in-Chief, Contemporary Jewry",
        "email": "hartman@rowan.edu",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "Editor of Contemporary Jewry, the flagship social-scientific journal of Jewish studies (ASSJ). Could commission a special issue or data article on GRID's Jewish mapping. Rowan University professor emerita.",
        "send_via": "hartman@rowan.edu",
        "subject_override": "GRID: A Complete Jewish Institutional GIS — Potential Data Article for Contemporary Jewry",
    },

    # ═══ TIER 2: UNIVERSITY OF TORONTO ═══
    {
        "org": "Anne Tanenbaum Centre for Jewish Studies (U of T)",
        "contact": "Anna Shternshis — Director, Al and Malka Green Professor of Yiddish Studies",
        "email": None,  # Centre email: cjs@utoronto.ca or via the general contact
        "phone": "416-978-1624",
        "sector": "Academic",
        "tier": 2,
        "notes": "DIRECTOR of ATCJS. Top academic contact. Research: Yiddish culture, Holocaust in USSR, Jewish diaspora. She decides research partnerships.",
        "send_via": "cjs@utoronto.ca",  # Anne Tanenbaum Centre general email
        "subject_override": "GRID: 25,000-Site Jewish Diaspora Map — Research Collaboration Opportunity",
    },
    {
        "org": "University of Toronto — Dept of Sociology",
        "contact": "Robert Brym — Professor, S.D. Clark Chair in Sociology",
        "email": "rbrym@chass.utoronto.ca",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "Jewish History & Social Sciences. Author of multiple books on Jewish communities. Would see immediate research value in the dataset.",
        "send_via": "rbrym@chass.utoronto.ca",
    },
    {
        "org": "University of Toronto — Holocaust Studies",
        "contact": "Doris L. Bergen — Chancellor Rose and Ray Wolfe Professor of Holocaust Studies",
        "email": "doris.bergen@utoronto.ca",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "Fellow of Royal Society of Canada. Holocaust geography & mapping applications for her research/teaching.",
        "send_via": "doris.bergen@utoronto.ca",
    },
    {
        "org": "University of Toronto — Dept of Geography & Planning",
        "contact": "Tamir Arviv — PhD (Geography, 'Diverse Geographies of Jewishness')",
        "email": None,
        "phone": None,
        "sector": "Academic",
        "tier": 3,
        "notes": "Wrote PhD thesis on Jewish geography/identity in Toronto. Most directly aligned research. May be reachable via Geography Dept.",
        "send_via": None,  # No email found — skip for now, research later
    },
    {
        "org": "Anne Tanenbaum Centre for Jewish Studies (U of T)",
        "contact": "ATCJS General / Postdoctoral Fellows (Farkas, Czendze, Zuckier)",
        "email": None,
        "phone": "416-978-1624",
        "sector": "Academic",
        "tier": 3,
        "notes": "Adam Farkas (Soviet Jewish migration), Oskar Czendze (Jewish diaspora/belonging), Shlomo Zuckier (ancient Judaism). All 2025-26 fellows.",
        "send_via": "cjs@utoronto.ca",
        "subject_override": "GRID: Jewish Infrastructure Dataset — For ATCJS Research Fellows",
    },

    # ═══ TIER 1: USCJ — United Synagogue of Conservative Judaism ═══
    {
        "org": "USCJ — United Synagogue of Conservative Judaism",
        "contact": "Barry Mael — Senior Director, Synagogue Affiliations",
        "email": "mael@uscj.org",
        "phone": "732-738-4302",
        "sector": "Umbrella / Denomination",
        "tier": 1,
        "notes": "Oversees synagogue relations for ~600 Conservative congregations. GRID has 329 Conservative entries mapped — direct buyer for congregational data.",
        "send_via": "mael@uscj.org",
        "subject_override": "GRID: Conservative Synagogue Mapping — Dataset for USCJ Congregational Planning",
    },
    {
        "org": "USCJ — United Synagogue of Conservative Judaism",
        "contact": "Martin S. Kunoff — Senior Leadership (NYC HQ)",
        "email": "kunoff@uscj.org",
        "phone": "646-519-9280",
        "sector": "Umbrella / Denomination",
        "tier": 1,
        "notes": "646 = NYC HQ area code. Likely senior operations/strategy. Secondary if Barry Mael doesn't respond.",
        "send_via": "kunoff@uscj.org",
        "subject_override": "GRID: Conservative Jewish Infrastructure Map — For USCJ Leadership",
    },
    {
        "org": "USCJ — United Synagogue of Conservative Judaism (Dept of Synagogue Success)",
        "contact": "Heather Vidmar-McEwen — Administrative Assistant, Dept of Synagogue Success",
        "email": "dssadmin@uscj.org",
        "phone": None,
        "sector": "Umbrella / Denomination",
        "tier": 2,
        "notes": "Synagogue Success department is the direct internal customer for data that helps congregations. Entry point to get routed to the right decision-maker.",
        "send_via": "dssadmin@uscj.org",
        "subject_override": "GRID: Synagogue Mapping Dataset — For USCJ Synagogue Success Team",
    },
    {
        "org": "USCJ — United Synagogue of Conservative Judaism",
        "contact": "Marc Sender — Senior Leadership (Midwest)",
        "email": "msender@uscj.org",
        "phone": "847-714-9130 ext. 101",
        "sector": "Umbrella / Denomination",
        "tier": 2,
        "notes": "847 = Chicago area. Ext 101 suggests senior position. Midwest Conservative synagogue hub.",
        "send_via": "msender@uscj.org",
    },

    # ═══ TIER 3: SECONDARY TORONTO ORGANIZATIONS ═══
    {
        "org": "Friends of Simon Wiesenthal Center (FSWC) — Toronto",
        "contact": "General",
        "email": None,
        "phone": None,
        "sector": "Education / Advocacy",
        "tier": 3,
        "notes": "Heritage/security mapping. Research contact info before sending.",
        "send_via": None,
    },
    {
        "org": "Jewish Immigrant Aid Services (JIAS) — Toronto",
        "contact": "General",
        "email": None,
        "phone": None,
        "sector": "Social Services",
        "tier": 3,
        "notes": "Diaspora mapping for immigrant settlement planning. Research contact info.",
        "send_via": None,
    },
    {
        "org": "Canadian Jewish News (CJN)",
        "contact": "Editorial",
        "email": None,
        "phone": None,
        "sector": "Media",
        "tier": 3,
        "notes": "Media coverage of the dataset. Could write about GRID's Jewish mapping.",
        "send_via": None,
    },

    # ═══ BONUS: U of T Map & Data Library ═══
    {
        "org": "University of Toronto — Map & Data Library",
        "contact": "GIS & Data Librarians",
        "email": None,
        "phone": None,
        "sector": "Academic / GIS",
        "tier": 3,
        "notes": "mdl.library.utoronto.ca — They manage geospatial data for U of T community. Could add GRID to their collection. Also: Scholars GeoPortal (Ontario-wide academic GIS).",
        "send_via": None,
    },

    # ═══ TIER 1: MAJOR US JEWISH FEDERATIONS (top metro areas) ═══
    {
        "org": "UJA-Federation of New York",
        "contact": "Federation Leadership — Community Planning",
        "email": "info@ujafedny.org",
        "phone": None,
        "sector": "Federation",
        "tier": 1,
        "notes": "Largest Jewish federation in the world. NYC metro has 16,630 Jewish entries in GRID. Community planning & security are direct buyers.",
        "send_via": "info@ujafedny.org",
        "subject_override": "GRID: 16,630 NY-Area Jewish Institutions Mapped — Dataset for UJA-NY Planning",
    },
    {
        "org": "Jewish Federation of Greater Los Angeles",
        "contact": "Federation Leadership / Community Security",
        "email": "info@jewishla.org",
        "phone": None,
        "sector": "Federation",
        "tier": 1,
        "notes": "Second-largest US Jewish community. Also: security@jewishla.org for the LA Community Security Program.",
        "send_via": "info@jewishla.org",
    },
    {
        "org": "Jewish United Fund of Chicago (JUF)",
        "contact": "Federation Leadership / Community Security",
        "email": "info@juf.org",
        "phone": None,
        "sector": "Federation",
        "tier": 1,
        "notes": "Chicago Jewish federation. Also: communitysecurity@juf.org for their security team.",
        "send_via": "info@juf.org",
    },
    {
        "org": "Combined Jewish Philanthropies (CJP) — Boston",
        "contact": "Federation Leadership",
        "email": "info@cjp.org",
        "phone": None,
        "sector": "Federation",
        "tier": 2,
        "notes": "Boston's Jewish federation. Home to Brandeis, Hebrew College, and major Jewish academic institutions.",
        "send_via": "info@cjp.org",
    },
    {
        "org": "Jewish Federation of Greater Philadelphia",
        "contact": "Federation Leadership",
        "email": "info@jewishphilly.org",
        "phone": None,
        "sector": "Federation",
        "tier": 2,
        "notes": "Major Northeast federation. Large Orthodox + Conservative populations.",
        "send_via": "info@jewishphilly.org",
    },
    {
        "org": "Jewish Federation of Greater Washington",
        "contact": "Federation Leadership",
        "email": "info@shalomdc.org",
        "phone": None,
        "sector": "Federation",
        "tier": 2,
        "notes": "DC metro federation. Proximity to federal government & policy makers makes data especially valuable here.",
        "send_via": "info@shalomdc.org",
    },
    {
        "org": "Jewish Federation of Greater Miami",
        "contact": "Federation Leadership",
        "email": "info@jewishmiami.org",
        "phone": None,
        "sector": "Federation",
        "tier": 2,
        "notes": "Major Southeast federation. Growing Orthodox & Latin American Jewish populations.",
        "send_via": "info@jewishmiami.org",
    },
    {
        "org": "Jewish Federation of Greater Atlanta",
        "contact": "Federation Leadership",
        "email": "info@jewishatlanta.org",
        "phone": None,
        "sector": "Federation",
        "tier": 2,
        "notes": "Fast-growing Southern Jewish community. GRID maps every synagogue, school, and JCC for community planning.",
        "send_via": "info@jewishatlanta.org",
    },
    {
        "org": "Jewish Federation of Greater Houston",
        "contact": "Federation Leadership",
        "email": "info@houstonjewish.org",
        "phone": None,
        "sector": "Federation",
        "tier": 2,
        "notes": "Major Texas Jewish community. Mapping especially valuable for disaster planning (hurricane-prone).",
        "send_via": "info@houstonjewish.org",
    },
    {
        "org": "Jewish Community Federation of San Francisco",
        "contact": "Federation Leadership",
        "email": "info@sfjcf.org",
        "phone": None,
        "sector": "Federation",
        "tier": 2,
        "notes": "Bay Area federation. Tech-forward community likely to value data-driven planning.",
        "send_via": "info@sfjcf.org",
    },

    # ═══ TIER 1: JEWISH SECURITY (national + city-level) ═══
    {
        "org": "Mitzpe Institute — Diaspora Security Practice",
        "contact": "Mordecai Zehavi — Director",
        "email": "info@mitzpe.org",
        "phone": None,
        "sector": "Security",
        "tier": 1,
        "notes": "Diaspora security think tank. GRID maps every Jewish institution worldwide — direct application for security vulnerability assessment and diaspora protection strategy.",
        "send_via": "info@mitzpe.org",
        "subject_override": "GRID: Global Jewish Institution Map — Every Site GPS-Located for Diaspora Security Planning",
    },
    {
        "org": "American Jewish Committee (AJC)",
        "contact": "AJC — Global Jewish Advocacy",
        "email": "ajc@ajc.org",
        "phone": None,
        "sector": "Advocacy / Policy",
        "tier": 1,
        "notes": "Premier global Jewish advocacy organization. Offices in 25+ countries. GRID's worldwide Jewish mapping directly supports their mission.",
        "send_via": "ajc@ajc.org",
        "subject_override": "GRID: Worldwide Jewish Infrastructure Map — Data for AJC Global Advocacy",
    },
    {
        "org": "Community Security Initiative (CSI) — NYC",
        "contact": "CSI Security Team",
        "email": "info@communitysecurityinitiative.org",
        "phone": None,
        "sector": "Security",
        "tier": 1,
        "notes": "NYC's Jewish community security hub. Covers the largest Jewish population outside Israel. GRID maps every institution they protect.",
        "send_via": "info@communitysecurityinitiative.org",
    },
    {
        "org": "LA Jewish Community Security Program",
        "contact": "Security Director — LA Federation",
        "email": "security@jewishla.org",
        "phone": None,
        "sector": "Security",
        "tier": 2,
        "notes": "LA's Jewish security team. Protecting the second-largest US Jewish community.",
        "send_via": "security@jewishla.org",
    },
    {
        "org": "Chicago Jewish Community Security (JUF)",
        "contact": "Security Director — JUF Chicago",
        "email": "communitysecurity@juf.org",
        "phone": None,
        "sector": "Security",
        "tier": 2,
        "notes": "Chicago's Jewish security team. Third-largest US Jewish community.",
        "send_via": "communitysecurity@juf.org",
    },

    # ═══ TIER 1: DENOMINATIONAL BODIES ═══
    {
        "org": "Reconstructing Judaism / Reconstructionist Rabbinical College",
        "contact": "Denominational Leadership",
        "email": "info@reconstructingjudaism.org",
        "phone": None,
        "sector": "Umbrella / Denomination",
        "tier": 2,
        "notes": "Smallest major denomination but growing. 37 Reconstructionist synagogues mapped. Data supports congregational planning.",
        "send_via": "info@reconstructingjudaism.org",
    },

    # ═══ TIER 1: RESEARCH & DATA ORGANIZATIONS ═══
    {
        "org": "American Jewish Population Project (AJPP) — Brandeis",
        "contact": "AJPP Research Team",
        "email": "ajpp@brandeis.edu",
        "phone": None,
        "sector": "Research / Data",
        "tier": 1,
        "notes": "Produces US Jewish population estimates by state & metro area. GRID is institutional ground-truth data — perfect complement to their survey estimates.",
        "send_via": "ajpp@brandeis.edu",
        "subject_override": "GRID: Jewish Institutional Data — Ground-Truth Complement to AJPP Population Estimates",
    },
    {
        "org": "Institute for Jewish Policy Research (JPR) — UK",
        "contact": "JPR Research Team",
        "email": "hello@jpr.org.uk",
        "phone": None,
        "sector": "Research / Data",
        "tier": 1,
        "notes": "Europe's leading Jewish policy research institute. GRID's European Jewish data (9,600+ sites) directly supports their research on European Jewish life.",
        "send_via": "hello@jpr.org.uk",
        "subject_override": "GRID: 9,600+ European Jewish Sites Mapped — Dataset for JPR Research",
    },

    # ═══ TIER 2: ACADEMIC CENTERS ═══
    {
        "org": "Hebrew Union College — Jewish Studies Research",
        "contact": "HUC Research / Library",
        "email": "info@huc.edu",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "Reform Judaism's seminary & research institution. Campuses in Cincinnati, NY, LA, Jerusalem. GRID supports their research on American Judaism.",
        "send_via": "info@huc.edu",
    },
    {
        "org": "Yeshiva University — Center for Israel Studies",
        "contact": "CIS Research Team",
        "email": "cis@yu.edu",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "Orthodox Jewish university. Center for Israel Studies researches Israel-diaspora relations — GRID maps the diaspora infrastructure.",
        "send_via": "cis@yu.edu",
    },
    {
        "org": "NYU — Taub Center for Israel Studies",
        "contact": "Taub Center Research Team",
        "email": "israelstudies@nyu.edu",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "NYU's Israel studies center. Research on Israel-diaspora connections benefits from GRID's global Jewish mapping.",
        "send_via": "israelstudies@nyu.edu",
    },
    {
        "org": "University of Maryland — Gildenhorn Institute for Israel Studies",
        "contact": "Gildenhorn Institute",
        "email": "israelstudies@umd.edu",
        "phone": None,
        "sector": "Academic",
        "tier": 2,
        "notes": "UMD's Israel studies center. Major hub for Israel-diaspora academic research.",
        "send_via": "israelstudies@umd.edu",
    },

    # ═══ TIER 2: GLOBAL / DIASPORA ═══
    {
        "org": "American Zionist Movement (AZM)",
        "contact": "AZM Leadership",
        "email": "azm@azm.org",
        "phone": None,
        "sector": "Diaspora / Israel",
        "tier": 2,
        "notes": "Umbrella for 30+ Zionist organizations. GRID maps Jewish diaspora infrastructure — directly relevant to Zionist movement work.",
        "send_via": "azm@azm.org",
    },
    {
        "org": "Hadassah — Women's Zionist Organization of America",
        "contact": "Hadassah National Office",
        "email": "info@hadassah.org",
        "phone": None,
        "sector": "Diaspora / Israel",
        "tier": 2,
        "notes": "Largest Jewish women's organization in the US (300K+ members). 1,000+ chapters. GRID maps Hadassah chapters alongside synagogues — community infrastructure view.",
        "send_via": "info@hadassah.org",
    },
    {
        "org": "B'nai B'rith International",
        "contact": "B'nai B'rith Leadership",
        "email": "info@bnaibrith.org",
        "phone": None,
        "sector": "Diaspora / Israel",
        "tier": 2,
        "notes": "Oldest Jewish service organization (founded 1843). Global presence. GRID maps Jewish community infrastructure worldwide.",
        "send_via": "info@bnaibrith.org",
    },

    # ═══ TIER 2: HERITAGE & PRESERVATION ═══
    {
        "org": "Jewish Heritage North America",
        "contact": "Heritage Preservation Team",
        "email": "info@jewishheritage.org",
        "phone": None,
        "sector": "Heritage / Museum",
        "tier": 2,
        "notes": "Dedicated to preserving Jewish heritage sites. GRID maps every historic synagogue and Jewish cemetery — their core asset inventory.",
        "send_via": "info@jewishheritage.org",
        "subject_override": "GRID: Jewish Heritage Sites Mapped — Every Synagogue & Cemetery GPS-Located",
    },
    {
        "org": "National Museum of American Jewish History",
        "contact": "Museum Research / Curatorial",
        "email": "info@nmajh.org",
        "phone": None,
        "sector": "Heritage / Museum",
        "tier": 2,
        "notes": "Philadelphia-based. GRID maps every American synagogue — valuable for exhibition research and public education.",
        "send_via": "info@nmajh.org",
    },
    {
        "org": "American Sephardi Federation",
        "contact": "ASF Leadership",
        "email": "asf@americansephardifederation.org",
        "phone": None,
        "sector": "Heritage / Museum",
        "tier": 2,
        "notes": "Represents Sephardic/Mizrahi Jewish communities. GRID has 629 Sephardic + 2 Mizrahi entries mapped — directly serves their constituency.",
        "send_via": "asf@americansephardifederation.org",
        "subject_override": "GRID: Sephardic & Mizrahi Synagogues Mapped — Dataset for American Sephardi Federation",
    },

    # ═══ TIER 3: MEDIA ═══
    {
        "org": "Jewish Telegraphic Agency (JTA)",
        "contact": "Editor — JTA News Desk",
        "email": "editor@jta.org",
        "phone": None,
        "sector": "Media",
        "tier": 3,
        "notes": "Wire service for Jewish news worldwide. GRID data could power JTA stories with maps and data journalism on Jewish communities.",
        "send_via": "editor@jta.org",
    },
    {
        "org": "Jewish Insider",
        "contact": "Editorial — Tips Desk",
        "email": "tips@jewishinsider.com",
        "phone": None,
        "sector": "Media",
        "tier": 3,
        "notes": "Influential Jewish political/business newsletter. GRID data could support their coverage of Jewish community infrastructure and philanthropy.",
        "send_via": "tips@jewishinsider.com",
    },
    {
        "org": "Jewish News Syndicate (JNS)",
        "contact": "Editor — JNS News Desk",
        "email": "editor@jns.org",
        "phone": None,
        "sector": "Media",
        "tier": 3,
        "notes": "Jewish news wire. GRID's global Jewish data could power data-driven stories on diaspora communities.",
        "send_via": "editor@jns.org",
    },
]

# ═══════════════════════════════════════════════════════════════
# PITCH TEMPLATES
# ═══════════════════════════════════════════════════════════════

# Template A: Federation / UJA / CIJA buyers
BODY_FEDERATION = """Hi {contact},

I'm the creator of GRID (Global Religious Infrastructure Database) — the most complete dataset on Jewish religious infrastructure in the modern world. I'll be starting at Trinity College, University of Toronto this fall, and I'd like to explore how this data could support UJA's planning and community security work in the GTA.

**What GRID contains:**
- **26,943 Jewish sites** across 172 countries — synagogues, Chabad houses, yeshivas, cemeteries, community centers
- **100% GPS coverage** — every site geocoded
- **326 Jewish institutions in the Toronto area**, classified by tradition (Orthodox, Reform, Conservative, Chabad, Sephardic, etc.)
- **454 Jewish sites across Canada** — Montreal (66), Toronto (56), North York (57), Thornhill (37), Ottawa (16)
- **3,044 Chabad centers worldwide** with full organizational hierarchy
- AI-verified classification across 12 canonical traditions
- 3,465 sites with phone/email/website contacts

**Why this matters for UJA:**
- **Community planning**: Map Jewish population distribution against institutional coverage — identify gaps where new synagogues/schools are needed
- **Security planning**: Know every Jewish institution in your jurisdiction with GPS precision for emergency response coordination
- **Israel engagement**: Track diaspora infrastructure globally — from Buenos Aires to Budapest
- **Fundraising & allocations**: Data-driven decisions about where to direct community resources

**I've prepared an interactive Jewish world map** and Toronto detail map showing every synagogue, Chabad house, and yeshiva — I'd be happy to walk you through it.

I'm at 843-504-4542 — would you have 15 minutes to see what this looks like?

Best,

{SIG}"""

# Template B: Academic / U of T
BODY_ACADEMIC = """Hi {contact},

I'm the creator of GRID (Global Religious Infrastructure Database) and I'll be starting at Trinity College, University of Toronto this fall. I'd like to explore research collaboration possibilities with the Anne Tanenbaum Centre for Jewish Studies.

GRID contains **26,943 geocoded Jewish sites** across 172 countries — the most complete spatial dataset on Jewish religious infrastructure ever assembled. Every synagogue, Chabad house, yeshiva, and cemetery is GPS-located and AI-classified across 12 canonical traditions.

**What makes this unique for Jewish studies research:**

- **Complete spatial coverage**: From New York (6,488 sites) to Morocco (55), every Jewish institution mapped. This enables quantitative diaspora geography for the first time.
- **Tradition-level classification**: Orthodox, Reform, Conservative, Chabad, Sephardic, Hasidic, Reconstructionist, Humanistic, Karaite, Mizrahi — all verified via DeepSeek AI with provenance logging
- **Hierarchy data**: 2,885 Chabad relationships (HQ → regional → local), synagogue-to-movement linkages
- **Temporal depth**: Multiple data sources from 2010-2026 allow tracking of institutional birth/death/movement
- **454 Canadian entries**: Detailed coverage of Toronto (326 sites), Montreal, Ottawa, Vancouver — with Census tract demographics

**Research applications I see:**
- Mapping the Jewish diaspora's institutional footprint over time
- Correlating synagogue location with immigration patterns
- Studying denominational geography (where Reform vs Orthodox vs Chabad are growing)
- Holocaust geography — mapping pre-war vs post-war institutional landscapes
- Toronto Jewish community spatial analysis (building on Tamir Arviv's PhD work on Jewish geographies of Toronto)

I've prepared an interactive **global Jewish map** and **Toronto detail map** that I'd be glad to share. I'm at 843-504-4542 — could we find 15 minutes to discuss?

Best,

{SIG}"""

# Template C: CIJA / Security
BODY_SECURITY = """Hi {contact},

I'm the creator of GRID (Global Religious Infrastructure Database) — the most complete dataset on Jewish infrastructure worldwide, with 26,943 sites mapped across 172 countries. I'll be at Trinity College, U of T this fall.

I'm reaching out because GRID has direct applications for community security planning:

- **326 Toronto-area Jewish institutions** mapped with GPS precision — every synagogue, Chabad house, yeshiva, school, and community center
- **Every site classified by tradition** (Orthodox, Reform, Chabad, Conservative, etc.) — allowing threat assessment by denomination
- **Hierarchy data**: Which institutions are linked (e.g., Chabad network), enabling coordinated security planning
- **Contact data**: 3,465 phone numbers, websites, and emails for rapid communication

For security professionals, knowing exactly where every Jewish institution is — and which movement it belongs to — is baseline situational awareness. GRID provides this for Toronto, Canada, and globally.

I've prepared an interactive Jewish world map and Toronto detail map. I'm at 843-504-4542 — would you have a few minutes to see what this covers?

Best,

{SIG}"""

# Template D: Foundation / Philanthropy
BODY_FOUNDATION = """Hi {contact},

I'm the creator of GRID (Global Religious Infrastructure Database) — the most complete spatial dataset on Jewish religious infrastructure in the modern world. I'll be starting at Trinity College, University of Toronto this fall.

GRID contains **26,943 geocoded Jewish sites** across 172 countries — every synagogue, Chabad house, yeshiva, cemetery, and community center — fully AI-classified across 12 canonical traditions.

**Why this matters for {org}:**

GRID enables data-driven Jewish philanthropy:

- **Strategic grantmaking**: See exactly where Jewish institutions are — and aren't. Map gaps in coverage before investing.
- **Impact measurement**: Track institutional birth, growth, and decline over time (2010-2026 data span) to measure grant effectiveness.
- **Diaspora intelligence**: From Buenos Aires to Budapest to Brooklyn — understand the global Jewish institutional landscape in one dataset.
- **Tradition-level granularity**: Know whether a community's infrastructure is Orthodox, Reform, Conservative, Chabad, or Sephardic — this determines what kinds of programs will succeed there.
- **Grantee bench-marking**: Compare grantee institutions against peers by location, denomination, and community demographics.

**Key stats:**
- 326 Jewish institutions in the Toronto area, 16,895 in the US, 2,214 in Israel
- 3,044 Chabad centers with full organizational hierarchy
- 3,465 sites with verified phone/email/website contacts
- 100% tradition-classified with AI provenance

This isn't a grant request — it's a data partnership. I've prepared interactive maps and I'm at 843-504-4542. Could we find 15 minutes?

Best,

{SIG}"""

# Template E: Short/General
BODY_SHORT = """Hi {contact},

I'm the creator of GRID — the most complete dataset on Jewish religious infrastructure worldwide: 26,943 synagogues, Chabad houses, yeshivas, and community centers across 172 countries, all GPS-mapped and AI-classified.

I'll be at Trinity College, University of Toronto this fall and I'd love to share the interactive Jewish world map with {org}. It covers 326 Jewish sites in the Toronto area alone.

Could we connect for 15 minutes? I'm at 843-504-4542.

Best,

{SIG}"""


def get_body(contact):
    """Select appropriate template based on sector."""
    sector = contact.get("sector", "")
    if sector in ("Federation", "Advocacy / Policy", "Security / Planning", "Federation / Security / Planning",
                  "Umbrella / Federation", "Umbrella / Denomination"):
        return BODY_FEDERATION
    elif sector in ("Academic", "Academic / Archive"):
        return BODY_ACADEMIC
    elif "Security" in sector:
        return BODY_SECURITY
    elif sector in ("Foundation", "Foundation Network", "Research / Data"):
        return BODY_FOUNDATION
    else:
        return BODY_SHORT


def send_email(to, subj, body):
    msg = MIMEMultipart()
    msg["From"] = FROM
    msg["To"] = to
    msg["Reply-To"] = REPLY_TO
    msg["Subject"] = subj
    msg.attach(MIMEText(body, "plain"))
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as s:
        s.starttls()
        s.login("charlesaprescottjr@gmail.com", PWD)
        s.send_message(msg)


# ═══════════════════════════════════════════════════════════════
# MAIN: BUILD & SEND
# ═══════════════════════════════════════════════════════════════

SENT_LOG = OUT / "jewish_toronto_sent.txt"
FAIL_LOG = OUT / "gmail_failed.txt"

# Load already sent
already = set()
if SENT_LOG.exists():
    for line in SENT_LOG.read_text().strip().split("\n"):
        if line.strip():
            already.add(line.strip().lower())

# Filter: only contacts with send_via, not already sent
ready = []
for c in CONTACTS:
    via = c.get("send_via")
    if via and via.lower() not in already:
        ready.append(c)

print(f"Toronto Jewish contacts: {len(CONTACTS)} total, {len(ready)} ready to send\n")
for tier in [1, 2, 3]:
    tier_contacts = [c for c in ready if c.get("tier") == tier]
    if tier_contacts:
        print(f"  Tier {tier}: {len(tier_contacts)} contacts")
        for c in tier_contacts:
            print(f"    {c['org'][:50]:50s} -> {c.get('send_via','(no email)')}")

print(f"\nStarting send (1 per {INTERVAL}s)...\n")

ok = fail = 0
for i, c in enumerate(ready):
    to = c["send_via"]
    subj = c.get("subject_override") or f"GRID: Jewish Infrastructure Dataset — For {c['contact']}"
    body = get_body(c).format(contact=c["contact"], org=c["org"], SIG=SIG)

    print(f"[{i+1}/{len(ready)}] {c['org'][:45]:45s} attn: {c['contact'][:30]:30s} -> {to}", end="", flush=True)
    try:
        send_email(to, subj, body)
        ok += 1
        with open(SENT_LOG, "a") as f:
            f.write(f"{to}|{c['org']}|{c['contact']}|{datetime.now().isoformat()}\n")
        print(f"  ✅ OK ({ok} sent, {fail} failed)")
    except Exception as e:
        fail += 1
        print(f"  ❌ FAIL: {str(e)[:80]}")
        with open(FAIL_LOG, "a") as f:
            f.write(f"{datetime.now().isoformat()},{to},{c['org']},{str(e)[:100]}\n")

    if i < len(ready) - 1:
        print(f"     Waiting {INTERVAL//60}m...")
        time.sleep(INTERVAL)

print(f"\n{'='*60}")
print(f"DONE: {ok} sent, {fail} failed")
print(f"{'='*60}")

# Print the outreach plan summary
print(f"""
╔══════════════════════════════════════════════════════════════════╗
║  TORONTO JEWISH OUTREACH — CAMPAIGN SUMMARY                     ║
╠══════════════════════════════════════════════════════════════════╣
║  Maps generated:                                                ║
║    map_jewish_global.html    — 25K Jewish sites worldwide       ║
║    map_jewish_toronto.html   — 326 Toronto-area institutions    ║
║    map_jewish_countries.html — Top 15 countries bar chart       ║
║    map_jewish_canada.html    — Canadian cities bar chart        ║
╠══════════════════════════════════════════════════════════════════╣
║  TIER 1 — Direct Buyers (2 orgs, 4 contacts):                   ║
║    UJA Federation (Adam Minsky, Ken Tanenbaum, Security Dir)    ║
║    CIJA (Catherine Morrow — BEST entry point)                   ║
╠══════════════════════════════════════════════════════════════════╣
║  TIER 2 — U of T (4 contacts):                                  ║
║    Anna Shternshis — Director, ATCJS (cjs@utoronto.ca)         ║
║    Robert Brym — Sociology (rbrym@chass.utoronto.ca)           ║
║    Doris Bergen — Holocaust Studies (doris.bergen@utoronto.ca) ║
║    ATCJS General / Postdocs (cjs@utoronto.ca)                  ║
╠══════════════════════════════════════════════════════════════════╣
║  TIER 3 — Needs research (5 orgs):                              ║
║    FSWC, JIAS, CJN, Tamir Arviv, Map & Data Library            ║
╠══════════════════════════════════════════════════════════════════╣
║  CALLS REQUIRED:                                                ║
║    UJA: 416-635-2883 — Ask for Adam Minsky's office            ║
║    UJA: 416-635-2883 — Ask for Director of Community Security  ║
║    CIJA: (416) 925-7499 x224 — Catherine Morrow                ║
║    ATCJS: 416-978-1624 — Anna Shternshis                       ║
╚══════════════════════════════════════════════════════════════════╝
""")
